// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssproto.proto

package smproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SSCmd int32

const (
	SSCmd_INVALID_CMD SSCmd = 0
	//agent && nameserver 1000 ~ 1999
	SSCmd_REQ_REGISTER_APP                  SSCmd = 1000
	SSCmd_RSP_REGISTER_APP                  SSCmd = 1001
	SSCmd_REQ_REGISTER_SERVICE              SSCmd = 1002
	SSCmd_RSP_REGISTER_SERVICE              SSCmd = 1003
	SSCmd_NOTIFY_SERVICE_ONLINE             SSCmd = 1004
	SSCmd_REQ_UNREGISTER_SERVICE            SSCmd = 1005
	SSCmd_NOTIFY_NAMESERVER_HEARTBEAT       SSCmd = 1006
	SSCmd_NOTIFY_NAMESERVER_SYNCATTR        SSCmd = 1007
	SSCmd_NOTIFY_SERVICE_SYNCATTR           SSCmd = 1008
	SSCmd_NOTIFY_NAMESERVER_ELECTION        SSCmd = 1009
	SSCmd_NOTIFY_SERVICE_ELECTION_RESULT    SSCmd = 1010
	SSCmd_NOTIFY_SERVICE_KICK_OFF           SSCmd = 1011
	SSCmd_NOTIFY_NAMESERVER_AGENT_INFO      SSCmd = 1012
	SSCmd_NOTIFY_NAMESERVER_REGISTER_ROUTER SSCmd = 1013
	//有状态服务扩缩容,2段提交流程
	SSCmd_REQ_AGENT_ROUTER_UPDATE      SSCmd = 1014
	SSCmd_RSP_NAMESERVER_ROUTER_UPDATE SSCmd = 1015
	//agent && agent 2000 ~ 2999
	SSCmd_NOTIFY_SERVICE_MESSAGE SSCmd = 2000
	SSCmd_REQ_PING_SERVICE       SSCmd = 2001
	SSCmd_RSP_PING_SERVICE       SSCmd = 2002
)

var SSCmd_name = map[int32]string{
	0:    "INVALID_CMD",
	1000: "REQ_REGISTER_APP",
	1001: "RSP_REGISTER_APP",
	1002: "REQ_REGISTER_SERVICE",
	1003: "RSP_REGISTER_SERVICE",
	1004: "NOTIFY_SERVICE_ONLINE",
	1005: "REQ_UNREGISTER_SERVICE",
	1006: "NOTIFY_NAMESERVER_HEARTBEAT",
	1007: "NOTIFY_NAMESERVER_SYNCATTR",
	1008: "NOTIFY_SERVICE_SYNCATTR",
	1009: "NOTIFY_NAMESERVER_ELECTION",
	1010: "NOTIFY_SERVICE_ELECTION_RESULT",
	1011: "NOTIFY_SERVICE_KICK_OFF",
	1012: "NOTIFY_NAMESERVER_AGENT_INFO",
	1013: "NOTIFY_NAMESERVER_REGISTER_ROUTER",
	1014: "REQ_AGENT_ROUTER_UPDATE",
	1015: "RSP_NAMESERVER_ROUTER_UPDATE",
	2000: "NOTIFY_SERVICE_MESSAGE",
	2001: "REQ_PING_SERVICE",
	2002: "RSP_PING_SERVICE",
}

var SSCmd_value = map[string]int32{
	"INVALID_CMD":                       0,
	"REQ_REGISTER_APP":                  1000,
	"RSP_REGISTER_APP":                  1001,
	"REQ_REGISTER_SERVICE":              1002,
	"RSP_REGISTER_SERVICE":              1003,
	"NOTIFY_SERVICE_ONLINE":             1004,
	"REQ_UNREGISTER_SERVICE":            1005,
	"NOTIFY_NAMESERVER_HEARTBEAT":       1006,
	"NOTIFY_NAMESERVER_SYNCATTR":        1007,
	"NOTIFY_SERVICE_SYNCATTR":           1008,
	"NOTIFY_NAMESERVER_ELECTION":        1009,
	"NOTIFY_SERVICE_ELECTION_RESULT":    1010,
	"NOTIFY_SERVICE_KICK_OFF":           1011,
	"NOTIFY_NAMESERVER_AGENT_INFO":      1012,
	"NOTIFY_NAMESERVER_REGISTER_ROUTER": 1013,
	"REQ_AGENT_ROUTER_UPDATE":           1014,
	"RSP_NAMESERVER_ROUTER_UPDATE":      1015,
	"NOTIFY_SERVICE_MESSAGE":            2000,
	"REQ_PING_SERVICE":                  2001,
	"RSP_PING_SERVICE":                  2002,
}

func (x SSCmd) String() string {
	return proto.EnumName(SSCmd_name, int32(x))
}

func (SSCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{0}
}

type SSError int32

const (
	SSError_OK                          SSError = 0
	SSError_ERR_APP_NOT_REGISTER        SSError = -1000
	SSError_ERR_SERVICE_REGISTER_AGAIN  SSError = -1001
	SSError_ERR_APP_SESSION_LOST        SSError = -1002
	SSError_ERR_ROUTER_PREPARE_ERR      SSError = -1003
	SSError_ERR_ROUTER_PREPARE_TIMEOUT  SSError = -1004
	SSError_ERR_SERVICE_REGISTER_LINEUP SSError = -1005
)

var SSError_name = map[int32]string{
	0:     "OK",
	-1000: "ERR_APP_NOT_REGISTER",
	-1001: "ERR_SERVICE_REGISTER_AGAIN",
	-1002: "ERR_APP_SESSION_LOST",
	-1003: "ERR_ROUTER_PREPARE_ERR",
	-1004: "ERR_ROUTER_PREPARE_TIMEOUT",
	-1005: "ERR_SERVICE_REGISTER_LINEUP",
}

var SSError_value = map[string]int32{
	"OK":                          0,
	"ERR_APP_NOT_REGISTER":        -1000,
	"ERR_SERVICE_REGISTER_AGAIN":  -1001,
	"ERR_APP_SESSION_LOST":        -1002,
	"ERR_ROUTER_PREPARE_ERR":      -1003,
	"ERR_ROUTER_PREPARE_TIMEOUT":  -1004,
	"ERR_SERVICE_REGISTER_LINEUP": -1005,
}

func (x SSError) String() string {
	return proto.EnumName(SSError_name, int32(x))
}

func (SSError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{1}
}

//agent与nameserver建立连接后同步agent信息
type NotifyNameServerAgentInfo struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`
	AppID                string   `protobuf:"bytes,2,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerAgentInfo) Reset()         { *m = NotifyNameServerAgentInfo{} }
func (m *NotifyNameServerAgentInfo) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerAgentInfo) ProtoMessage()    {}
func (*NotifyNameServerAgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{0}
}

func (m *NotifyNameServerAgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerAgentInfo.Unmarshal(m, b)
}
func (m *NotifyNameServerAgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerAgentInfo.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerAgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerAgentInfo.Merge(m, src)
}
func (m *NotifyNameServerAgentInfo) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerAgentInfo.Size(m)
}
func (m *NotifyNameServerAgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerAgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerAgentInfo proto.InternalMessageInfo

func (m *NotifyNameServerAgentInfo) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *NotifyNameServerAgentInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

//注册App相关
type ReqRegisterApp struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`
	AppID                string   `protobuf:"bytes,2,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegisterApp) Reset()         { *m = ReqRegisterApp{} }
func (m *ReqRegisterApp) String() string { return proto.CompactTextString(m) }
func (*ReqRegisterApp) ProtoMessage()    {}
func (*ReqRegisterApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{1}
}

func (m *ReqRegisterApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegisterApp.Unmarshal(m, b)
}
func (m *ReqRegisterApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegisterApp.Marshal(b, m, deterministic)
}
func (m *ReqRegisterApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegisterApp.Merge(m, src)
}
func (m *ReqRegisterApp) XXX_Size() int {
	return xxx_messageInfo_ReqRegisterApp.Size(m)
}
func (m *ReqRegisterApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegisterApp.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegisterApp proto.InternalMessageInfo

func (m *ReqRegisterApp) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *ReqRegisterApp) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type RspRegisterApp struct {
	Leaders              []*ServiceInfo `protobuf:"bytes,1,rep,name=Leaders,proto3" json:"Leaders,omitempty"`
	Result               int32          `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RspRegisterApp) Reset()         { *m = RspRegisterApp{} }
func (m *RspRegisterApp) String() string { return proto.CompactTextString(m) }
func (*RspRegisterApp) ProtoMessage()    {}
func (*RspRegisterApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{2}
}

func (m *RspRegisterApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRegisterApp.Unmarshal(m, b)
}
func (m *RspRegisterApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRegisterApp.Marshal(b, m, deterministic)
}
func (m *RspRegisterApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRegisterApp.Merge(m, src)
}
func (m *RspRegisterApp) XXX_Size() int {
	return xxx_messageInfo_RspRegisterApp.Size(m)
}
func (m *RspRegisterApp) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRegisterApp.DiscardUnknown(m)
}

var xxx_messageInfo_RspRegisterApp proto.InternalMessageInfo

func (m *RspRegisterApp) GetLeaders() []*ServiceInfo {
	if m != nil {
		return m.Leaders
	}
	return nil
}

func (m *RspRegisterApp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//注册/注销服务相关
type ServiceInfo struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceId            uint64   `protobuf:"varint,2,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	AddrHandle           uint64   `protobuf:"varint,3,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{3}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceInfo) GetServiceId() uint64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ServiceInfo) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

type ServiceOptions struct {
	ConsistentHashKey    uint64   `protobuf:"varint,1,opt,name=ConsistentHashKey,proto3" json:"ConsistentHashKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOptions) Reset()         { *m = ServiceOptions{} }
func (m *ServiceOptions) String() string { return proto.CompactTextString(m) }
func (*ServiceOptions) ProtoMessage()    {}
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{4}
}

func (m *ServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOptions.Unmarshal(m, b)
}
func (m *ServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOptions.Marshal(b, m, deterministic)
}
func (m *ServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOptions.Merge(m, src)
}
func (m *ServiceOptions) XXX_Size() int {
	return xxx_messageInfo_ServiceOptions.Size(m)
}
func (m *ServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOptions proto.InternalMessageInfo

func (m *ServiceOptions) GetConsistentHashKey() uint64 {
	if m != nil {
		return m.ConsistentHashKey
	}
	return 0
}

type ReqRegisterService struct {
	ServiceInfo          *ServiceInfo    `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Options              *ServiceOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqRegisterService) Reset()         { *m = ReqRegisterService{} }
func (m *ReqRegisterService) String() string { return proto.CompactTextString(m) }
func (*ReqRegisterService) ProtoMessage()    {}
func (*ReqRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{5}
}

func (m *ReqRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegisterService.Unmarshal(m, b)
}
func (m *ReqRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegisterService.Marshal(b, m, deterministic)
}
func (m *ReqRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegisterService.Merge(m, src)
}
func (m *ReqRegisterService) XXX_Size() int {
	return xxx_messageInfo_ReqRegisterService.Size(m)
}
func (m *ReqRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegisterService proto.InternalMessageInfo

func (m *ReqRegisterService) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *ReqRegisterService) GetOptions() *ServiceOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type RspRegisterService struct {
	AddrHandle           uint64   `protobuf:"varint,1,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspRegisterService) Reset()         { *m = RspRegisterService{} }
func (m *RspRegisterService) String() string { return proto.CompactTextString(m) }
func (*RspRegisterService) ProtoMessage()    {}
func (*RspRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{6}
}

func (m *RspRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRegisterService.Unmarshal(m, b)
}
func (m *RspRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRegisterService.Marshal(b, m, deterministic)
}
func (m *RspRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRegisterService.Merge(m, src)
}
func (m *RspRegisterService) XXX_Size() int {
	return xxx_messageInfo_RspRegisterService.Size(m)
}
func (m *RspRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_RspRegisterService proto.InternalMessageInfo

func (m *RspRegisterService) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

func (m *RspRegisterService) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ReqUnRegisterService struct {
	AddrHandle           uint64   `protobuf:"varint,1,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnRegisterService) Reset()         { *m = ReqUnRegisterService{} }
func (m *ReqUnRegisterService) String() string { return proto.CompactTextString(m) }
func (*ReqUnRegisterService) ProtoMessage()    {}
func (*ReqUnRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{7}
}

func (m *ReqUnRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnRegisterService.Unmarshal(m, b)
}
func (m *ReqUnRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnRegisterService.Marshal(b, m, deterministic)
}
func (m *ReqUnRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnRegisterService.Merge(m, src)
}
func (m *ReqUnRegisterService) XXX_Size() int {
	return xxx_messageInfo_ReqUnRegisterService.Size(m)
}
func (m *ReqUnRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnRegisterService proto.InternalMessageInfo

func (m *ReqUnRegisterService) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

//通知服务上下线相关
type NotifyServiceOnline struct {
	ServerAddr           string          `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`
	ServiceInfo          *ServiceInfo    `protobuf:"bytes,2,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Options              *ServiceOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	IsOnline             bool            `protobuf:"varint,4,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NotifyServiceOnline) Reset()         { *m = NotifyServiceOnline{} }
func (m *NotifyServiceOnline) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceOnline) ProtoMessage()    {}
func (*NotifyServiceOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{8}
}

func (m *NotifyServiceOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceOnline.Unmarshal(m, b)
}
func (m *NotifyServiceOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceOnline.Marshal(b, m, deterministic)
}
func (m *NotifyServiceOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceOnline.Merge(m, src)
}
func (m *NotifyServiceOnline) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceOnline.Size(m)
}
func (m *NotifyServiceOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceOnline.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceOnline proto.InternalMessageInfo

func (m *NotifyServiceOnline) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *NotifyServiceOnline) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *NotifyServiceOnline) GetOptions() *ServiceOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *NotifyServiceOnline) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

//跨进程服务消息通知
type NotifyServiceMessage struct {
	SrcService           *ServiceInfo `protobuf:"bytes,1,opt,name=src_service,json=srcService,proto3" json:"src_service,omitempty"`
	DstHandle            uint64       `protobuf:"varint,2,opt,name=dst_handle,json=dstHandle,proto3" json:"dst_handle,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceMessage) Reset()         { *m = NotifyServiceMessage{} }
func (m *NotifyServiceMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceMessage) ProtoMessage()    {}
func (*NotifyServiceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{9}
}

func (m *NotifyServiceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceMessage.Unmarshal(m, b)
}
func (m *NotifyServiceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceMessage.Marshal(b, m, deterministic)
}
func (m *NotifyServiceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceMessage.Merge(m, src)
}
func (m *NotifyServiceMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceMessage.Size(m)
}
func (m *NotifyServiceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceMessage proto.InternalMessageInfo

func (m *NotifyServiceMessage) GetSrcService() *ServiceInfo {
	if m != nil {
		return m.SrcService
	}
	return nil
}

func (m *NotifyServiceMessage) GetDstHandle() uint64 {
	if m != nil {
		return m.DstHandle
	}
	return 0
}

func (m *NotifyServiceMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//Agent服务与NameServer心跳
type NotifyNameServerHeartBeat struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerHeartBeat) Reset()         { *m = NotifyNameServerHeartBeat{} }
func (m *NotifyNameServerHeartBeat) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerHeartBeat) ProtoMessage()    {}
func (*NotifyNameServerHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{10}
}

func (m *NotifyNameServerHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Unmarshal(m, b)
}
func (m *NotifyNameServerHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerHeartBeat.Merge(m, src)
}
func (m *NotifyNameServerHeartBeat) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Size(m)
}
func (m *NotifyNameServerHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerHeartBeat proto.InternalMessageInfo

func (m *NotifyNameServerHeartBeat) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

//通过NameServer同步Service属性变更
type NotifyNameServerSyncAttr struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerSyncAttr) Reset()         { *m = NotifyNameServerSyncAttr{} }
func (m *NotifyNameServerSyncAttr) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerSyncAttr) ProtoMessage()    {}
func (*NotifyNameServerSyncAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{11}
}

func (m *NotifyNameServerSyncAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Unmarshal(m, b)
}
func (m *NotifyNameServerSyncAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerSyncAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerSyncAttr.Merge(m, src)
}
func (m *NotifyNameServerSyncAttr) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Size(m)
}
func (m *NotifyNameServerSyncAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerSyncAttr.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerSyncAttr proto.InternalMessageInfo

func (m *NotifyNameServerSyncAttr) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

func (m *NotifyNameServerSyncAttr) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//NameServer同步Agent Service属性变更
type NotifyServiceSyncAttr struct {
	ServiceInfo          *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceSyncAttr) Reset()         { *m = NotifyServiceSyncAttr{} }
func (m *NotifyServiceSyncAttr) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceSyncAttr) ProtoMessage()    {}
func (*NotifyServiceSyncAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{12}
}

func (m *NotifyServiceSyncAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceSyncAttr.Unmarshal(m, b)
}
func (m *NotifyServiceSyncAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceSyncAttr.Marshal(b, m, deterministic)
}
func (m *NotifyServiceSyncAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceSyncAttr.Merge(m, src)
}
func (m *NotifyServiceSyncAttr) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceSyncAttr.Size(m)
}
func (m *NotifyServiceSyncAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceSyncAttr.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceSyncAttr proto.InternalMessageInfo

func (m *NotifyServiceSyncAttr) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *NotifyServiceSyncAttr) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//通知NameServer竞选leader
type NotifyNameServerElection struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	Event                int32    `protobuf:"varint,2,opt,name=Event,proto3" json:"Event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerElection) Reset()         { *m = NotifyNameServerElection{} }
func (m *NotifyNameServerElection) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerElection) ProtoMessage()    {}
func (*NotifyNameServerElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{13}
}

func (m *NotifyNameServerElection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerElection.Unmarshal(m, b)
}
func (m *NotifyNameServerElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerElection.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerElection.Merge(m, src)
}
func (m *NotifyNameServerElection) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerElection.Size(m)
}
func (m *NotifyNameServerElection) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerElection.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerElection proto.InternalMessageInfo

func (m *NotifyNameServerElection) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

func (m *NotifyNameServerElection) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

//NameServer通知Service选举结果
type NotifyServiceElectionResult struct {
	Candidate            *ServiceInfo `protobuf:"bytes,1,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
	Event                int32        `protobuf:"varint,2,opt,name=Event,proto3" json:"Event,omitempty"`
	Result               int32        `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceElectionResult) Reset()         { *m = NotifyServiceElectionResult{} }
func (m *NotifyServiceElectionResult) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceElectionResult) ProtoMessage()    {}
func (*NotifyServiceElectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{14}
}

func (m *NotifyServiceElectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceElectionResult.Unmarshal(m, b)
}
func (m *NotifyServiceElectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceElectionResult.Marshal(b, m, deterministic)
}
func (m *NotifyServiceElectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceElectionResult.Merge(m, src)
}
func (m *NotifyServiceElectionResult) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceElectionResult.Size(m)
}
func (m *NotifyServiceElectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceElectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceElectionResult proto.InternalMessageInfo

func (m *NotifyServiceElectionResult) GetCandidate() *ServiceInfo {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *NotifyServiceElectionResult) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

func (m *NotifyServiceElectionResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//NameServer强踢某Service下线
type NotifyServiceKickOff struct {
	AddrHandle           uint64   `protobuf:"varint,1,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyServiceKickOff) Reset()         { *m = NotifyServiceKickOff{} }
func (m *NotifyServiceKickOff) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceKickOff) ProtoMessage()    {}
func (*NotifyServiceKickOff) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{15}
}

func (m *NotifyServiceKickOff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceKickOff.Unmarshal(m, b)
}
func (m *NotifyServiceKickOff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceKickOff.Marshal(b, m, deterministic)
}
func (m *NotifyServiceKickOff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceKickOff.Merge(m, src)
}
func (m *NotifyServiceKickOff) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceKickOff.Size(m)
}
func (m *NotifyServiceKickOff) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceKickOff.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceKickOff proto.InternalMessageInfo

func (m *NotifyServiceKickOff) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

//NameServer通知Agent 有状态服务实例扩容
type ReqAgentRouterUpdate struct {
	Cmd                  int32    `protobuf:"varint,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAgentRouterUpdate) Reset()         { *m = ReqAgentRouterUpdate{} }
func (m *ReqAgentRouterUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqAgentRouterUpdate) ProtoMessage()    {}
func (*ReqAgentRouterUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{16}
}

func (m *ReqAgentRouterUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAgentRouterUpdate.Unmarshal(m, b)
}
func (m *ReqAgentRouterUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAgentRouterUpdate.Marshal(b, m, deterministic)
}
func (m *ReqAgentRouterUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAgentRouterUpdate.Merge(m, src)
}
func (m *ReqAgentRouterUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqAgentRouterUpdate.Size(m)
}
func (m *ReqAgentRouterUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAgentRouterUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAgentRouterUpdate proto.InternalMessageInfo

func (m *ReqAgentRouterUpdate) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *ReqAgentRouterUpdate) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

//Agent回复NameServer 有状态服务实例扩容
type RspNameServerRouterUpdate struct {
	Result               int32    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspNameServerRouterUpdate) Reset()         { *m = RspNameServerRouterUpdate{} }
func (m *RspNameServerRouterUpdate) String() string { return proto.CompactTextString(m) }
func (*RspNameServerRouterUpdate) ProtoMessage()    {}
func (*RspNameServerRouterUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{17}
}

func (m *RspNameServerRouterUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspNameServerRouterUpdate.Unmarshal(m, b)
}
func (m *RspNameServerRouterUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspNameServerRouterUpdate.Marshal(b, m, deterministic)
}
func (m *RspNameServerRouterUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspNameServerRouterUpdate.Merge(m, src)
}
func (m *RspNameServerRouterUpdate) XXX_Size() int {
	return xxx_messageInfo_RspNameServerRouterUpdate.Size(m)
}
func (m *RspNameServerRouterUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_RspNameServerRouterUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_RspNameServerRouterUpdate proto.InternalMessageInfo

func (m *RspNameServerRouterUpdate) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RspNameServerRouterUpdate) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

//Agent通知NameServer注册路由
type NotifyNameServerRegisterRouter struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerRegisterRouter) Reset()         { *m = NotifyNameServerRegisterRouter{} }
func (m *NotifyNameServerRegisterRouter) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerRegisterRouter) ProtoMessage()    {}
func (*NotifyNameServerRegisterRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{18}
}

func (m *NotifyNameServerRegisterRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerRegisterRouter.Unmarshal(m, b)
}
func (m *NotifyNameServerRegisterRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerRegisterRouter.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerRegisterRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerRegisterRouter.Merge(m, src)
}
func (m *NotifyNameServerRegisterRouter) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerRegisterRouter.Size(m)
}
func (m *NotifyNameServerRegisterRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerRegisterRouter.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerRegisterRouter proto.InternalMessageInfo

func (m *NotifyNameServerRegisterRouter) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

//Agent服务间Ping包
type ReqServicePing struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	DstHandle            uint64   `protobuf:"varint,2,opt,name=DstHandle,proto3" json:"DstHandle,omitempty"`
	SrcServerAddr        string   `protobuf:"bytes,3,opt,name=SrcServerAddr,proto3" json:"SrcServerAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqServicePing) Reset()         { *m = ReqServicePing{} }
func (m *ReqServicePing) String() string { return proto.CompactTextString(m) }
func (*ReqServicePing) ProtoMessage()    {}
func (*ReqServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{19}
}

func (m *ReqServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqServicePing.Unmarshal(m, b)
}
func (m *ReqServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqServicePing.Marshal(b, m, deterministic)
}
func (m *ReqServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqServicePing.Merge(m, src)
}
func (m *ReqServicePing) XXX_Size() int {
	return xxx_messageInfo_ReqServicePing.Size(m)
}
func (m *ReqServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_ReqServicePing proto.InternalMessageInfo

func (m *ReqServicePing) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ReqServicePing) GetDstHandle() uint64 {
	if m != nil {
		return m.DstHandle
	}
	return 0
}

func (m *ReqServicePing) GetSrcServerAddr() string {
	if m != nil {
		return m.SrcServerAddr
	}
	return ""
}

type RspServicePing struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	SrcHandle            uint64   `protobuf:"varint,2,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspServicePing) Reset()         { *m = RspServicePing{} }
func (m *RspServicePing) String() string { return proto.CompactTextString(m) }
func (*RspServicePing) ProtoMessage()    {}
func (*RspServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{20}
}

func (m *RspServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspServicePing.Unmarshal(m, b)
}
func (m *RspServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspServicePing.Marshal(b, m, deterministic)
}
func (m *RspServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspServicePing.Merge(m, src)
}
func (m *RspServicePing) XXX_Size() int {
	return xxx_messageInfo_RspServicePing.Size(m)
}
func (m *RspServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_RspServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_RspServicePing proto.InternalMessageInfo

func (m *RspServicePing) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RspServicePing) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

type SSMsg struct {
	Cmd SSCmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=smproto.SSCmd" json:"cmd,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*SSMsg_RegisterAppReq
	//	*SSMsg_RegisterAppRsp
	//	*SSMsg_RegisterServiceReq
	//	*SSMsg_RegisterServiceRsp
	//	*SSMsg_NotifyServiceOnline
	//	*SSMsg_UnregisterServiceReq
	//	*SSMsg_NotifyNameserverHb
	//	*SSMsg_NotifyNameserverAttr
	//	*SSMsg_NotifyServiceAttr
	//	*SSMsg_NotifyNameserverElection
	//	*SSMsg_NotifyServiceElectionResult
	//	*SSMsg_NotifyServiceKickoff
	//	*SSMsg_NotifyNameserverAgentInfo
	//	*SSMsg_NotifyNameserverRegisterRouter
	//	*SSMsg_AgentRouterUpdateReq
	//	*SSMsg_NameserverRouterUpdateRsp
	//	*SSMsg_NotifyServiceMessage
	//	*SSMsg_ServicePingReq
	//	*SSMsg_ServicePingRsp
	Msg                  isSSMsg_Msg `protobuf_oneof:"Msg"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SSMsg) Reset()         { *m = SSMsg{} }
func (m *SSMsg) String() string { return proto.CompactTextString(m) }
func (*SSMsg) ProtoMessage()    {}
func (*SSMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{21}
}

func (m *SSMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSMsg.Unmarshal(m, b)
}
func (m *SSMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSMsg.Marshal(b, m, deterministic)
}
func (m *SSMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSMsg.Merge(m, src)
}
func (m *SSMsg) XXX_Size() int {
	return xxx_messageInfo_SSMsg.Size(m)
}
func (m *SSMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SSMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SSMsg proto.InternalMessageInfo

func (m *SSMsg) GetCmd() SSCmd {
	if m != nil {
		return m.Cmd
	}
	return SSCmd_INVALID_CMD
}

type isSSMsg_Msg interface {
	isSSMsg_Msg()
}

type SSMsg_RegisterAppReq struct {
	RegisterAppReq *ReqRegisterApp `protobuf:"bytes,100,opt,name=register_app_req,json=registerAppReq,proto3,oneof"`
}

type SSMsg_RegisterAppRsp struct {
	RegisterAppRsp *RspRegisterApp `protobuf:"bytes,101,opt,name=register_app_rsp,json=registerAppRsp,proto3,oneof"`
}

type SSMsg_RegisterServiceReq struct {
	RegisterServiceReq *ReqRegisterService `protobuf:"bytes,102,opt,name=register_service_req,json=registerServiceReq,proto3,oneof"`
}

type SSMsg_RegisterServiceRsp struct {
	RegisterServiceRsp *RspRegisterService `protobuf:"bytes,103,opt,name=register_service_rsp,json=registerServiceRsp,proto3,oneof"`
}

type SSMsg_NotifyServiceOnline struct {
	NotifyServiceOnline *NotifyServiceOnline `protobuf:"bytes,104,opt,name=notify_service_online,json=notifyServiceOnline,proto3,oneof"`
}

type SSMsg_UnregisterServiceReq struct {
	UnregisterServiceReq *ReqUnRegisterService `protobuf:"bytes,105,opt,name=unregister_service_req,json=unregisterServiceReq,proto3,oneof"`
}

type SSMsg_NotifyNameserverHb struct {
	NotifyNameserverHb *NotifyNameServerHeartBeat `protobuf:"bytes,106,opt,name=notify_nameserver_hb,json=notifyNameserverHb,proto3,oneof"`
}

type SSMsg_NotifyNameserverAttr struct {
	NotifyNameserverAttr *NotifyNameServerSyncAttr `protobuf:"bytes,107,opt,name=notify_nameserver_attr,json=notifyNameserverAttr,proto3,oneof"`
}

type SSMsg_NotifyServiceAttr struct {
	NotifyServiceAttr *NotifyServiceSyncAttr `protobuf:"bytes,108,opt,name=notify_service_attr,json=notifyServiceAttr,proto3,oneof"`
}

type SSMsg_NotifyNameserverElection struct {
	NotifyNameserverElection *NotifyNameServerElection `protobuf:"bytes,109,opt,name=notify_nameserver_election,json=notifyNameserverElection,proto3,oneof"`
}

type SSMsg_NotifyServiceElectionResult struct {
	NotifyServiceElectionResult *NotifyServiceElectionResult `protobuf:"bytes,110,opt,name=notify_service_election_result,json=notifyServiceElectionResult,proto3,oneof"`
}

type SSMsg_NotifyServiceKickoff struct {
	NotifyServiceKickoff *NotifyServiceKickOff `protobuf:"bytes,111,opt,name=notify_service_kickoff,json=notifyServiceKickoff,proto3,oneof"`
}

type SSMsg_NotifyNameserverAgentInfo struct {
	NotifyNameserverAgentInfo *NotifyNameServerAgentInfo `protobuf:"bytes,112,opt,name=notify_nameserver_agent_info,json=notifyNameserverAgentInfo,proto3,oneof"`
}

type SSMsg_NotifyNameserverRegisterRouter struct {
	NotifyNameserverRegisterRouter *NotifyNameServerRegisterRouter `protobuf:"bytes,113,opt,name=notify_nameserver_register_router,json=notifyNameserverRegisterRouter,proto3,oneof"`
}

type SSMsg_AgentRouterUpdateReq struct {
	AgentRouterUpdateReq *ReqAgentRouterUpdate `protobuf:"bytes,114,opt,name=agent_router_update_req,json=agentRouterUpdateReq,proto3,oneof"`
}

type SSMsg_NameserverRouterUpdateRsp struct {
	NameserverRouterUpdateRsp *RspNameServerRouterUpdate `protobuf:"bytes,115,opt,name=nameserver_router_update_rsp,json=nameserverRouterUpdateRsp,proto3,oneof"`
}

type SSMsg_NotifyServiceMessage struct {
	NotifyServiceMessage *NotifyServiceMessage `protobuf:"bytes,200,opt,name=notify_service_message,json=notifyServiceMessage,proto3,oneof"`
}

type SSMsg_ServicePingReq struct {
	ServicePingReq *ReqServicePing `protobuf:"bytes,201,opt,name=service_ping_req,json=servicePingReq,proto3,oneof"`
}

type SSMsg_ServicePingRsp struct {
	ServicePingRsp *RspServicePing `protobuf:"bytes,202,opt,name=service_ping_rsp,json=servicePingRsp,proto3,oneof"`
}

func (*SSMsg_RegisterAppReq) isSSMsg_Msg() {}

func (*SSMsg_RegisterAppRsp) isSSMsg_Msg() {}

func (*SSMsg_RegisterServiceReq) isSSMsg_Msg() {}

func (*SSMsg_RegisterServiceRsp) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceOnline) isSSMsg_Msg() {}

func (*SSMsg_UnregisterServiceReq) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverHb) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverAttr) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceAttr) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverElection) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceElectionResult) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceKickoff) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverAgentInfo) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverRegisterRouter) isSSMsg_Msg() {}

func (*SSMsg_AgentRouterUpdateReq) isSSMsg_Msg() {}

func (*SSMsg_NameserverRouterUpdateRsp) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceMessage) isSSMsg_Msg() {}

func (*SSMsg_ServicePingReq) isSSMsg_Msg() {}

func (*SSMsg_ServicePingRsp) isSSMsg_Msg() {}

func (m *SSMsg) GetMsg() isSSMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SSMsg) GetRegisterAppReq() *ReqRegisterApp {
	if x, ok := m.GetMsg().(*SSMsg_RegisterAppReq); ok {
		return x.RegisterAppReq
	}
	return nil
}

func (m *SSMsg) GetRegisterAppRsp() *RspRegisterApp {
	if x, ok := m.GetMsg().(*SSMsg_RegisterAppRsp); ok {
		return x.RegisterAppRsp
	}
	return nil
}

func (m *SSMsg) GetRegisterServiceReq() *ReqRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_RegisterServiceReq); ok {
		return x.RegisterServiceReq
	}
	return nil
}

func (m *SSMsg) GetRegisterServiceRsp() *RspRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_RegisterServiceRsp); ok {
		return x.RegisterServiceRsp
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceOnline() *NotifyServiceOnline {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceOnline); ok {
		return x.NotifyServiceOnline
	}
	return nil
}

func (m *SSMsg) GetUnregisterServiceReq() *ReqUnRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_UnregisterServiceReq); ok {
		return x.UnregisterServiceReq
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverHb() *NotifyNameServerHeartBeat {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverHb); ok {
		return x.NotifyNameserverHb
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverAttr() *NotifyNameServerSyncAttr {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverAttr); ok {
		return x.NotifyNameserverAttr
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceAttr() *NotifyServiceSyncAttr {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceAttr); ok {
		return x.NotifyServiceAttr
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverElection() *NotifyNameServerElection {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverElection); ok {
		return x.NotifyNameserverElection
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceElectionResult() *NotifyServiceElectionResult {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceElectionResult); ok {
		return x.NotifyServiceElectionResult
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceKickoff() *NotifyServiceKickOff {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceKickoff); ok {
		return x.NotifyServiceKickoff
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverAgentInfo() *NotifyNameServerAgentInfo {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverAgentInfo); ok {
		return x.NotifyNameserverAgentInfo
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverRegisterRouter() *NotifyNameServerRegisterRouter {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverRegisterRouter); ok {
		return x.NotifyNameserverRegisterRouter
	}
	return nil
}

func (m *SSMsg) GetAgentRouterUpdateReq() *ReqAgentRouterUpdate {
	if x, ok := m.GetMsg().(*SSMsg_AgentRouterUpdateReq); ok {
		return x.AgentRouterUpdateReq
	}
	return nil
}

func (m *SSMsg) GetNameserverRouterUpdateRsp() *RspNameServerRouterUpdate {
	if x, ok := m.GetMsg().(*SSMsg_NameserverRouterUpdateRsp); ok {
		return x.NameserverRouterUpdateRsp
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceMessage() *NotifyServiceMessage {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceMessage); ok {
		return x.NotifyServiceMessage
	}
	return nil
}

func (m *SSMsg) GetServicePingReq() *ReqServicePing {
	if x, ok := m.GetMsg().(*SSMsg_ServicePingReq); ok {
		return x.ServicePingReq
	}
	return nil
}

func (m *SSMsg) GetServicePingRsp() *RspServicePing {
	if x, ok := m.GetMsg().(*SSMsg_ServicePingRsp); ok {
		return x.ServicePingRsp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SSMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SSMsg_RegisterAppReq)(nil),
		(*SSMsg_RegisterAppRsp)(nil),
		(*SSMsg_RegisterServiceReq)(nil),
		(*SSMsg_RegisterServiceRsp)(nil),
		(*SSMsg_NotifyServiceOnline)(nil),
		(*SSMsg_UnregisterServiceReq)(nil),
		(*SSMsg_NotifyNameserverHb)(nil),
		(*SSMsg_NotifyNameserverAttr)(nil),
		(*SSMsg_NotifyServiceAttr)(nil),
		(*SSMsg_NotifyNameserverElection)(nil),
		(*SSMsg_NotifyServiceElectionResult)(nil),
		(*SSMsg_NotifyServiceKickoff)(nil),
		(*SSMsg_NotifyNameserverAgentInfo)(nil),
		(*SSMsg_NotifyNameserverRegisterRouter)(nil),
		(*SSMsg_AgentRouterUpdateReq)(nil),
		(*SSMsg_NameserverRouterUpdateRsp)(nil),
		(*SSMsg_NotifyServiceMessage)(nil),
		(*SSMsg_ServicePingReq)(nil),
		(*SSMsg_ServicePingRsp)(nil),
	}
}

func init() {
	proto.RegisterEnum("smproto.SSCmd", SSCmd_name, SSCmd_value)
	proto.RegisterEnum("smproto.SSError", SSError_name, SSError_value)
	proto.RegisterType((*NotifyNameServerAgentInfo)(nil), "smproto.NotifyNameServerAgentInfo")
	proto.RegisterType((*ReqRegisterApp)(nil), "smproto.ReqRegisterApp")
	proto.RegisterType((*RspRegisterApp)(nil), "smproto.RspRegisterApp")
	proto.RegisterType((*ServiceInfo)(nil), "smproto.ServiceInfo")
	proto.RegisterType((*ServiceOptions)(nil), "smproto.ServiceOptions")
	proto.RegisterType((*ReqRegisterService)(nil), "smproto.ReqRegisterService")
	proto.RegisterType((*RspRegisterService)(nil), "smproto.RspRegisterService")
	proto.RegisterType((*ReqUnRegisterService)(nil), "smproto.ReqUnRegisterService")
	proto.RegisterType((*NotifyServiceOnline)(nil), "smproto.NotifyServiceOnline")
	proto.RegisterType((*NotifyServiceMessage)(nil), "smproto.NotifyServiceMessage")
	proto.RegisterType((*NotifyNameServerHeartBeat)(nil), "smproto.NotifyNameServerHeartBeat")
	proto.RegisterType((*NotifyNameServerSyncAttr)(nil), "smproto.NotifyNameServerSyncAttr")
	proto.RegisterType((*NotifyServiceSyncAttr)(nil), "smproto.NotifyServiceSyncAttr")
	proto.RegisterType((*NotifyNameServerElection)(nil), "smproto.NotifyNameServerElection")
	proto.RegisterType((*NotifyServiceElectionResult)(nil), "smproto.NotifyServiceElectionResult")
	proto.RegisterType((*NotifyServiceKickOff)(nil), "smproto.NotifyServiceKickOff")
	proto.RegisterType((*ReqAgentRouterUpdate)(nil), "smproto.ReqAgentRouterUpdate")
	proto.RegisterType((*RspNameServerRouterUpdate)(nil), "smproto.RspNameServerRouterUpdate")
	proto.RegisterType((*NotifyNameServerRegisterRouter)(nil), "smproto.NotifyNameServerRegisterRouter")
	proto.RegisterType((*ReqServicePing)(nil), "smproto.ReqServicePing")
	proto.RegisterType((*RspServicePing)(nil), "smproto.RspServicePing")
	proto.RegisterType((*SSMsg)(nil), "smproto.SSMsg")
}

func init() { proto.RegisterFile("ssproto.proto", fileDescriptor_38a3ff22a5566682) }

var fileDescriptor_38a3ff22a5566682 = []byte{
	// 1515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0x96, 0x2c, 0x3b, 0x8a, 0x8f, 0x13, 0x9b, 0x99, 0xc8, 0x0e, 0xfd, 0x88, 0xaf, 0xad, 0x04,
	0x37, 0x46, 0x70, 0x61, 0xe0, 0xba, 0x68, 0x8b, 0x6e, 0x8a, 0xd2, 0x32, 0x6d, 0xa9, 0x96, 0x29,
	0x65, 0x48, 0x19, 0xcd, 0x8a, 0x60, 0xa4, 0x91, 0xcc, 0xda, 0x22, 0x69, 0x0e, 0x1d, 0x20, 0xab,
	0xf6, 0x3f, 0xf4, 0xf9, 0x3f, 0xba, 0xef, 0xba, 0xed, 0xaa, 0xe9, 0xaf, 0xe8, 0xfb, 0xfd, 0xc8,
	0xae, 0xc5, 0x0c, 0xdf, 0x0f, 0xdb, 0x69, 0xb4, 0x10, 0xc8, 0x33, 0x67, 0xbe, 0xf3, 0x9d, 0x6f,
	0xce, 0x9c, 0x43, 0xb8, 0x4e, 0xa9, 0xe3, 0xda, 0x9e, 0xbd, 0xc9, 0xff, 0x51, 0x95, 0x8e, 0xf9,
	0x43, 0xfd, 0x01, 0x2c, 0x2a, 0xb6, 0x67, 0x0e, 0x9f, 0x28, 0xc6, 0x98, 0xa8, 0xc4, 0x7d, 0x4c,
	0x5c, 0x69, 0x44, 0x2c, 0xaf, 0x65, 0x0d, 0x6d, 0xb4, 0x0a, 0x10, 0x98, 0x06, 0x03, 0x57, 0x2c,
	0xaf, 0x95, 0x37, 0xa6, 0x71, 0xc2, 0x82, 0x6a, 0x30, 0x25, 0x39, 0x4e, 0x6b, 0x47, 0x9c, 0xe0,
	0x4b, 0xfe, 0x4b, 0x7d, 0x17, 0x66, 0x31, 0x39, 0xc5, 0x64, 0x64, 0x52, 0x8f, 0xb8, 0x92, 0xe3,
	0xbc, 0x20, 0xce, 0x5b, 0x30, 0x8b, 0xa9, 0x93, 0xc4, 0xd9, 0x84, 0x6a, 0x9b, 0x18, 0x03, 0xe2,
	0x52, 0xb1, 0xbc, 0x56, 0xd9, 0x98, 0xd9, 0xaa, 0x6d, 0x06, 0x79, 0x6c, 0x32, 0x34, 0xb3, 0x4f,
	0x18, 0x6d, 0x1c, 0x3a, 0xa1, 0x05, 0xb8, 0x82, 0x09, 0x3d, 0x3b, 0xf1, 0x38, 0xf0, 0x14, 0x0e,
	0xde, 0xea, 0x63, 0x98, 0x49, 0xf8, 0xa3, 0xb5, 0xe8, 0x95, 0x89, 0x10, 0xf0, 0x4b, 0x9a, 0xd0,
	0x0a, 0x4c, 0x87, 0x1b, 0x06, 0x1c, 0x6b, 0x12, 0xc7, 0x06, 0x96, 0x1e, 0x4b, 0xa3, 0x69, 0x58,
	0x83, 0x13, 0x22, 0x56, 0xf8, 0x72, 0xc2, 0x52, 0x7f, 0x1d, 0x66, 0x03, 0xe7, 0x8e, 0xe3, 0x99,
	0xb6, 0x45, 0xd1, 0xff, 0xe0, 0x46, 0xc3, 0xb6, 0x28, 0x4b, 0xcc, 0xf2, 0x9a, 0x06, 0x3d, 0xda,
	0x27, 0x4f, 0x78, 0xdc, 0x49, 0x9c, 0x5f, 0xa8, 0xbf, 0x5b, 0x06, 0x94, 0x50, 0x34, 0xc0, 0x42,
	0xaf, 0xc2, 0x35, 0xea, 0x3f, 0xea, 0xa6, 0x35, 0xb4, 0xf9, 0xfe, 0xf3, 0x24, 0x99, 0xa1, 0x89,
	0x7c, 0xff, 0x0f, 0x55, 0xdb, 0x27, 0xc2, 0x73, 0x99, 0xd9, 0xba, 0x95, 0xdd, 0x13, 0xf0, 0xc4,
	0xa1, 0x5f, 0xbd, 0x0d, 0x28, 0x71, 0x16, 0x21, 0x83, 0x74, 0xe2, 0xe5, 0x6c, 0xe2, 0xe7, 0xea,
	0xff, 0x0a, 0xd4, 0x30, 0x39, 0xed, 0x59, 0xff, 0x12, 0xaf, 0xfe, 0x69, 0x19, 0x6e, 0xfa, 0xd5,
	0x1a, 0xf2, 0xb4, 0x4e, 0x4c, 0x8b, 0x5c, 0x5a, 0x5f, 0x59, 0xa5, 0x26, 0x5e, 0x40, 0xa9, 0xca,
	0xf3, 0x29, 0x85, 0x96, 0x61, 0xda, 0xa4, 0xba, 0xcd, 0x89, 0x89, 0x93, 0x6b, 0xe5, 0x8d, 0xab,
	0xf8, 0xaa, 0x49, 0x7d, 0xa2, 0xec, 0x24, 0x6b, 0xa9, 0x04, 0x0e, 0x08, 0xa5, 0xc6, 0x88, 0xa0,
	0x97, 0x61, 0x86, 0xba, 0x7d, 0x3d, 0x88, 0x7d, 0xe1, 0x51, 0x02, 0x75, 0xfb, 0xa1, 0x60, 0xb7,
	0x01, 0x06, 0xd4, 0xd3, 0x8f, 0x7c, 0xc1, 0x82, 0xc2, 0x1c, 0x50, 0x2f, 0xd0, 0x1f, 0xc1, 0xe4,
	0xc0, 0xf0, 0x0c, 0xce, 0xfd, 0x1a, 0xe6, 0xcf, 0xf5, 0xd7, 0xf2, 0x17, 0xbe, 0x49, 0x0c, 0xd7,
	0xdb, 0x26, 0x86, 0xc7, 0xeb, 0xdc, 0xed, 0xa7, 0xf4, 0x8f, 0x0d, 0xf5, 0x36, 0x88, 0xd9, 0xad,
	0xea, 0x13, 0xab, 0x2f, 0x79, 0x9e, 0x7b, 0xf1, 0xce, 0x88, 0xc8, 0x44, 0x82, 0xc8, 0x00, 0xe6,
	0x53, 0x52, 0x44, 0x50, 0x2f, 0x5c, 0xd7, 0x45, 0x51, 0x94, 0x3c, 0x67, 0xf9, 0x84, 0xf4, 0xd9,
	0x59, 0x5d, 0xc2, 0xb9, 0x06, 0x53, 0xf2, 0x63, 0x62, 0x85, 0xb5, 0xeb, 0xbf, 0xd4, 0xdf, 0x81,
	0xe5, 0x14, 0xeb, 0x10, 0xcc, 0xaf, 0x6c, 0xb4, 0x05, 0xd3, 0x0d, 0xc3, 0x1a, 0x98, 0x03, 0xc3,
	0xbb, 0xf8, 0x14, 0x63, 0xb7, 0xe2, 0x40, 0x89, 0xbb, 0x53, 0xc9, 0xde, 0x9d, 0x14, 0x81, 0x7d,
	0xb3, 0x7f, 0xdc, 0x19, 0x0e, 0x2f, 0xbd, 0x3b, 0x6f, 0xf2, 0x3b, 0xc7, 0x7b, 0x3b, 0xb6, 0xcf,
	0x3c, 0xe2, 0xf6, 0x1c, 0x1e, 0x5d, 0x80, 0x4a, 0x63, 0x3c, 0xe0, 0x1b, 0xa6, 0x30, 0x7b, 0xcc,
	0xb6, 0xc3, 0x89, 0x5c, 0x3b, 0xac, 0xf7, 0x60, 0x11, 0x53, 0x27, 0x56, 0x34, 0x05, 0x18, 0x13,
	0x2f, 0x27, 0x89, 0x3f, 0x07, 0xec, 0x36, 0xac, 0x66, 0xcf, 0x2a, 0xec, 0x10, 0x7e, 0x84, 0xcb,
	0x3b, 0x75, 0x7d, 0xc8, 0x87, 0x4f, 0x60, 0xe9, 0x9a, 0xd6, 0x88, 0x25, 0xa8, 0x92, 0xd3, 0x40,
	0x11, 0xf6, 0xc8, 0xce, 0x7d, 0x27, 0xbc, 0x23, 0xe1, 0xa5, 0x89, 0x0c, 0xe8, 0x2e, 0x5c, 0x57,
	0xfd, 0x1b, 0x16, 0xf4, 0x93, 0x0a, 0x8f, 0x92, 0x36, 0xd6, 0xdf, 0xe0, 0xc3, 0xe9, 0xd2, 0x38,
	0x71, 0x7d, 0x4d, 0x64, 0x6f, 0xd3, 0x27, 0xd7, 0x61, 0x4a, 0x55, 0x0f, 0xe8, 0x08, 0xad, 0x41,
	0xa5, 0x1f, 0x1c, 0xc1, 0xec, 0xd6, 0x6c, 0x5c, 0x2e, 0x6a, 0x63, 0x3c, 0xc0, 0x6c, 0x09, 0x35,
	0x40, 0x70, 0x03, 0x25, 0x74, 0xc3, 0x71, 0x74, 0x97, 0x9c, 0x8a, 0x83, 0x4c, 0x43, 0x4a, 0xcf,
	0xdc, 0x66, 0x09, 0xcf, 0xba, 0xf1, 0x2b, 0x26, 0xa7, 0x79, 0x10, 0xea, 0x88, 0x24, 0x0b, 0x92,
	0x1a, 0xb8, 0x59, 0x10, 0xea, 0xa0, 0x0e, 0xd4, 0x22, 0x90, 0xf0, 0x96, 0x32, 0x36, 0x43, 0x0e,
	0xb4, 0x5c, 0xc4, 0x26, 0x10, 0xa9, 0x59, 0xc2, 0xc8, 0x4d, 0x9b, 0x18, 0xab, 0x42, 0x40, 0xea,
	0x88, 0xa3, 0x2c, 0x60, 0x6e, 0xfc, 0x14, 0x01, 0x52, 0x07, 0x61, 0x98, 0xb7, 0x78, 0x15, 0x45,
	0x70, 0x41, 0x33, 0x3e, 0xe2, 0x88, 0x2b, 0x11, 0x62, 0xc1, 0x24, 0x69, 0x96, 0xf0, 0x4d, 0xab,
	0x60, 0xc0, 0xf4, 0x60, 0xe1, 0xcc, 0x2a, 0xcc, 0xdb, 0xe4, 0xa0, 0xb7, 0x93, 0x79, 0xe7, 0xe6,
	0x5a, 0xb3, 0x84, 0x6b, 0xf1, 0xf6, 0x44, 0xee, 0x87, 0x50, 0x0b, 0xa8, 0x5a, 0xc6, 0x98, 0x50,
	0x5e, 0x5d, 0xfa, 0xd1, 0x23, 0xf1, 0x6d, 0x0e, 0x5a, 0xcf, 0x30, 0x2d, 0x68, 0xd8, 0x4c, 0x02,
	0x2b, 0x5a, 0xf4, 0x01, 0x9a, 0x8f, 0xd0, 0x43, 0x58, 0xc8, 0xe3, 0x1a, 0x9e, 0xe7, 0x8a, 0xc7,
	0x1c, 0x79, 0xfd, 0x5c, 0xe4, 0xb0, 0x09, 0x33, 0xca, 0x59, 0x60, 0xde, 0x9c, 0xbb, 0x70, 0x33,
	0xa3, 0x2e, 0xc7, 0x3d, 0xe1, 0xb8, 0xab, 0xc5, 0xda, 0x26, 0x40, 0x6f, 0xa4, 0xd4, 0xe5, 0x88,
	0x06, 0x2c, 0xe5, 0xc9, 0x92, 0xa0, 0xad, 0x8a, 0xe3, 0x4b, 0x08, 0x87, 0xfd, 0xb7, 0x59, 0xc2,
	0x62, 0x96, 0x70, 0xd4, 0xe8, 0x8f, 0x61, 0x35, 0x43, 0x3a, 0xc4, 0xd7, 0x5d, 0xbf, 0x55, 0x59,
	0x3c, 0xcc, 0xdd, 0x62, 0xfe, 0xe9, 0x1e, 0xdf, 0x2c, 0xe1, 0x65, 0xeb, 0x82, 0x11, 0xd0, 0x8b,
	0xc4, 0x0f, 0x83, 0x1d, 0x9b, 0xfd, 0x63, 0x7b, 0x38, 0x14, 0xed, 0x4c, 0xad, 0x14, 0xf5, 0xf1,
	0x58, 0xf8, 0x84, 0xdd, 0x1e, 0x0e, 0x11, 0x81, 0x95, 0x82, 0x33, 0x65, 0xed, 0xdc, 0x9f, 0x92,
	0xce, 0x25, 0x35, 0x13, 0x7d, 0xd5, 0x37, 0x4b, 0x78, 0x31, 0x77, 0xb4, 0xd1, 0x27, 0xbf, 0x07,
	0xeb, 0xf9, 0x30, 0x51, 0xe5, 0xbb, 0xbc, 0x0d, 0x8b, 0xa7, 0x3c, 0xd6, 0xbd, 0x73, 0x63, 0xa5,
	0xbb, 0x76, 0xb3, 0x84, 0x57, 0xb3, 0x01, 0x33, 0x7d, 0xfd, 0x10, 0x6e, 0xf9, 0xa9, 0xf8, 0x01,
	0xf4, 0x33, 0x3e, 0x4a, 0xf8, 0x05, 0x73, 0xf3, 0x17, 0x2c, 0x37, 0xc4, 0x98, 0x68, 0x46, 0xd6,
	0xc8, 0x2e, 0x18, 0x13, 0x2d, 0x91, 0x46, 0x1a, 0x9c, 0x3a, 0x22, 0xcd, 0x88, 0x76, 0xee, 0x54,
	0xe3, 0xa2, 0xc5, 0xec, 0x93, 0x61, 0xa8, 0x83, 0x0e, 0x73, 0x47, 0x3e, 0xf6, 0xbf, 0xeb, 0xc4,
	0xcf, 0xca, 0x17, 0x9d, 0x79, 0xf0, 0xf5, 0x97, 0x3b, 0xf3, 0xf0, 0xab, 0x70, 0x07, 0x84, 0x10,
	0xd0, 0x31, 0xad, 0x11, 0xd7, 0xe3, 0xf3, 0x72, 0xbe, 0xef, 0x27, 0xc6, 0x10, 0x6b, 0xd9, 0x34,
	0x7e, 0x65, 0x22, 0xe4, 0x50, 0xa8, 0x23, 0x7e, 0x51, 0xce, 0x37, 0xfe, 0x0b, 0x50, 0xa8, 0xb3,
	0x3d, 0x05, 0x95, 0x03, 0x3a, 0xba, 0xff, 0x74, 0x92, 0x4d, 0x2d, 0xf6, 0x99, 0x30, 0x07, 0x33,
	0x2d, 0xe5, 0x50, 0x6a, 0xb7, 0x76, 0xf4, 0xc6, 0xc1, 0x8e, 0x50, 0x42, 0xf3, 0x20, 0x60, 0xf9,
	0x81, 0x8e, 0xe5, 0xbd, 0x96, 0xaa, 0xc9, 0x58, 0x97, 0xba, 0x5d, 0xe1, 0xeb, 0x2a, 0x37, 0xab,
	0xdd, 0xb4, 0xf9, 0x9b, 0x2a, 0x5a, 0x84, 0x5a, 0xca, 0x5b, 0x95, 0xf1, 0x61, 0xab, 0x21, 0x0b,
	0xdf, 0xfa, 0x4b, 0xc9, 0x1d, 0xe1, 0xd2, 0x77, 0x55, 0xb4, 0x04, 0xf3, 0x4a, 0x47, 0x6b, 0xed,
	0x3e, 0x0c, 0x8d, 0x7a, 0x47, 0x69, 0xb7, 0x14, 0x59, 0xf8, 0xbe, 0x8a, 0x96, 0x61, 0x81, 0x21,
	0xf6, 0x94, 0xdc, 0xc6, 0x1f, 0xaa, 0x68, 0x0d, 0x96, 0x83, 0x8d, 0x8a, 0x74, 0x20, 0xb3, 0x05,
	0x19, 0xeb, 0x4d, 0x59, 0xc2, 0xda, 0xb6, 0x2c, 0x69, 0xc2, 0x8f, 0x55, 0xf4, 0x1f, 0x58, 0xca,
	0x7b, 0xa8, 0x0f, 0x95, 0x86, 0xa4, 0x69, 0x58, 0xf8, 0xa9, 0x8a, 0x56, 0xe0, 0x56, 0x26, 0x76,
	0xb4, 0xfa, 0xf3, 0x39, 0xdb, 0xe5, 0xb6, 0xdc, 0xd0, 0x5a, 0x1d, 0x45, 0xf8, 0xa5, 0x8a, 0xee,
	0xc0, 0x6a, 0x66, 0x7b, 0xb8, 0xaa, 0x63, 0x59, 0xed, 0xb5, 0x35, 0xe1, 0xd7, 0xa2, 0x18, 0xfb,
	0xad, 0xc6, 0xbe, 0xde, 0xd9, 0xdd, 0x15, 0x7e, 0xab, 0xa2, 0x75, 0x58, 0xc9, 0xc7, 0x90, 0xf6,
	0x64, 0x45, 0xd3, 0x5b, 0xca, 0x6e, 0x47, 0xf8, 0xbd, 0x8a, 0xfe, 0x0b, 0xeb, 0x79, 0x97, 0x48,
	0x10, 0xdc, 0xe9, 0x69, 0x32, 0x16, 0xfe, 0xe0, 0x81, 0x98, 0x58, 0xfe, 0x66, 0xdf, 0xac, 0xf7,
	0xba, 0x3b, 0x92, 0x26, 0x0b, 0x7f, 0xf2, 0x40, 0xec, 0x04, 0x92, 0x10, 0x29, 0x97, 0xbf, 0xb8,
	0xda, 0x19, 0xa6, 0x07, 0xb2, 0xaa, 0x4a, 0x7b, 0xb2, 0xf0, 0xe5, 0x5c, 0x58, 0x0a, 0xdd, 0x96,
	0xb2, 0x17, 0x1d, 0xc2, 0xd3, 0xb9, 0xb0, 0x14, 0x52, 0xe6, 0xaf, 0xe6, 0xee, 0x3f, 0x2b, 0x43,
	0x55, 0x55, 0x65, 0xd7, 0xb5, 0x5d, 0x74, 0x05, 0x26, 0x3a, 0xfb, 0x42, 0x09, 0xad, 0x43, 0x4d,
	0xc6, 0xbc, 0x58, 0x74, 0xa5, 0xa3, 0x45, 0x19, 0x08, 0x1f, 0x3f, 0xfb, 0xdb, 0xff, 0x95, 0xd1,
	0x3d, 0x58, 0x62, 0x2e, 0x61, 0xf8, 0xb8, 0xc0, 0xf6, 0xa4, 0x96, 0x22, 0x7c, 0x14, 0x3b, 0x26,
	0xb0, 0x54, 0x59, 0x55, 0x99, 0xe2, 0xed, 0x8e, 0xaa, 0x09, 0x1f, 0xc6, 0x2e, 0x77, 0x60, 0x81,
	0xb9, 0x04, 0x59, 0x76, 0xb1, 0xdc, 0x95, 0xb0, 0xac, 0xcb, 0x18, 0x0b, 0x1f, 0xe4, 0x02, 0x66,
	0x9c, 0xb4, 0xd6, 0x81, 0xdc, 0xe9, 0x69, 0xc2, 0xfb, 0xb1, 0xe3, 0x06, 0x2c, 0x17, 0x32, 0x63,
	0x95, 0xda, 0xeb, 0x0a, 0xef, 0x45, 0x9e, 0x8f, 0xae, 0xf0, 0xdb, 0xf7, 0xd2, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xff, 0x19, 0xbc, 0xe0, 0x9f, 0x11, 0x00, 0x00,
}
