// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssproto.proto

package smproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SSCmd int32

const (
	SSCmd_INVALID_CMD SSCmd = 0
	//agent && nameserver 1000 ~ 1999
	SSCmd_REQ_REGISTER_APP               SSCmd = 1000
	SSCmd_RSP_REGISTER_APP               SSCmd = 1001
	SSCmd_REQ_REGISTER_SERVICE           SSCmd = 1002
	SSCmd_RSP_REGISTER_SERVICE           SSCmd = 1003
	SSCmd_NOTIFY_SERVICE_ONLINE          SSCmd = 1004
	SSCmd_REQ_UNREGISTER_SERVICE         SSCmd = 1005
	SSCmd_NOTIFY_NAMESERVER_HEARTBEAT    SSCmd = 1006
	SSCmd_NOTIFY_NAMESERVER_SYNCATTR     SSCmd = 1007
	SSCmd_NOTIFY_SERVICE_SYNCATTR        SSCmd = 1008
	SSCmd_NOTIFY_NAMESERVER_ELECTION     SSCmd = 1009
	SSCmd_NOTIFY_SERVICE_ELECTION_RESULT SSCmd = 1010
	//agent && agent 2000 ~ 2999
	SSCmd_NOTIFY_SERVICE_MESSAGE SSCmd = 2000
	SSCmd_REQ_PING_SERVICE       SSCmd = 2001
	SSCmd_RSP_PING_SERVICE       SSCmd = 2002
)

var SSCmd_name = map[int32]string{
	0:    "INVALID_CMD",
	1000: "REQ_REGISTER_APP",
	1001: "RSP_REGISTER_APP",
	1002: "REQ_REGISTER_SERVICE",
	1003: "RSP_REGISTER_SERVICE",
	1004: "NOTIFY_SERVICE_ONLINE",
	1005: "REQ_UNREGISTER_SERVICE",
	1006: "NOTIFY_NAMESERVER_HEARTBEAT",
	1007: "NOTIFY_NAMESERVER_SYNCATTR",
	1008: "NOTIFY_SERVICE_SYNCATTR",
	1009: "NOTIFY_NAMESERVER_ELECTION",
	1010: "NOTIFY_SERVICE_ELECTION_RESULT",
	2000: "NOTIFY_SERVICE_MESSAGE",
	2001: "REQ_PING_SERVICE",
	2002: "RSP_PING_SERVICE",
}

var SSCmd_value = map[string]int32{
	"INVALID_CMD":                    0,
	"REQ_REGISTER_APP":               1000,
	"RSP_REGISTER_APP":               1001,
	"REQ_REGISTER_SERVICE":           1002,
	"RSP_REGISTER_SERVICE":           1003,
	"NOTIFY_SERVICE_ONLINE":          1004,
	"REQ_UNREGISTER_SERVICE":         1005,
	"NOTIFY_NAMESERVER_HEARTBEAT":    1006,
	"NOTIFY_NAMESERVER_SYNCATTR":     1007,
	"NOTIFY_SERVICE_SYNCATTR":        1008,
	"NOTIFY_NAMESERVER_ELECTION":     1009,
	"NOTIFY_SERVICE_ELECTION_RESULT": 1010,
	"NOTIFY_SERVICE_MESSAGE":         2000,
	"REQ_PING_SERVICE":               2001,
	"RSP_PING_SERVICE":               2002,
}

func (x SSCmd) String() string {
	return proto.EnumName(SSCmd_name, int32(x))
}

func (SSCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{0}
}

type SSError int32

const (
	SSError_OK                         SSError = 0
	SSError_ERR_APP_NOT_REGISTER       SSError = -1000
	SSError_ERR_SERVICE_REGISTER_AGAIN SSError = -1001
	SSError_ERR_APP_SESSION_LOST       SSError = -1002
)

var SSError_name = map[int32]string{
	0:     "OK",
	-1000: "ERR_APP_NOT_REGISTER",
	-1001: "ERR_SERVICE_REGISTER_AGAIN",
	-1002: "ERR_APP_SESSION_LOST",
}

var SSError_value = map[string]int32{
	"OK":                         0,
	"ERR_APP_NOT_REGISTER":       -1000,
	"ERR_SERVICE_REGISTER_AGAIN": -1001,
	"ERR_APP_SESSION_LOST":       -1002,
}

func (x SSError) String() string {
	return proto.EnumName(SSError_name, int32(x))
}

func (SSError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{1}
}

//注册App相关
type ReqRegisterApp struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`
	AppID                string   `protobuf:"bytes,2,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegisterApp) Reset()         { *m = ReqRegisterApp{} }
func (m *ReqRegisterApp) String() string { return proto.CompactTextString(m) }
func (*ReqRegisterApp) ProtoMessage()    {}
func (*ReqRegisterApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{0}
}

func (m *ReqRegisterApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegisterApp.Unmarshal(m, b)
}
func (m *ReqRegisterApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegisterApp.Marshal(b, m, deterministic)
}
func (m *ReqRegisterApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegisterApp.Merge(m, src)
}
func (m *ReqRegisterApp) XXX_Size() int {
	return xxx_messageInfo_ReqRegisterApp.Size(m)
}
func (m *ReqRegisterApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegisterApp.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegisterApp proto.InternalMessageInfo

func (m *ReqRegisterApp) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *ReqRegisterApp) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type RspRegisterApp struct {
	Result               int32    `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspRegisterApp) Reset()         { *m = RspRegisterApp{} }
func (m *RspRegisterApp) String() string { return proto.CompactTextString(m) }
func (*RspRegisterApp) ProtoMessage()    {}
func (*RspRegisterApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{1}
}

func (m *RspRegisterApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRegisterApp.Unmarshal(m, b)
}
func (m *RspRegisterApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRegisterApp.Marshal(b, m, deterministic)
}
func (m *RspRegisterApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRegisterApp.Merge(m, src)
}
func (m *RspRegisterApp) XXX_Size() int {
	return xxx_messageInfo_RspRegisterApp.Size(m)
}
func (m *RspRegisterApp) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRegisterApp.DiscardUnknown(m)
}

var xxx_messageInfo_RspRegisterApp proto.InternalMessageInfo

func (m *RspRegisterApp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//注册/注销服务相关
type ServiceInfo struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceId            uint64   `protobuf:"varint,2,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	AddrHandle           uint64   `protobuf:"varint,3,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{2}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceInfo) GetServiceId() uint64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ServiceInfo) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

type ReqRegisterService struct {
	ServiceInfo          *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqRegisterService) Reset()         { *m = ReqRegisterService{} }
func (m *ReqRegisterService) String() string { return proto.CompactTextString(m) }
func (*ReqRegisterService) ProtoMessage()    {}
func (*ReqRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{3}
}

func (m *ReqRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegisterService.Unmarshal(m, b)
}
func (m *ReqRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegisterService.Marshal(b, m, deterministic)
}
func (m *ReqRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegisterService.Merge(m, src)
}
func (m *ReqRegisterService) XXX_Size() int {
	return xxx_messageInfo_ReqRegisterService.Size(m)
}
func (m *ReqRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegisterService proto.InternalMessageInfo

func (m *ReqRegisterService) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

type RspRegisterService struct {
	AddrHandle           uint64   `protobuf:"varint,1,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	Result               int32    `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspRegisterService) Reset()         { *m = RspRegisterService{} }
func (m *RspRegisterService) String() string { return proto.CompactTextString(m) }
func (*RspRegisterService) ProtoMessage()    {}
func (*RspRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{4}
}

func (m *RspRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRegisterService.Unmarshal(m, b)
}
func (m *RspRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRegisterService.Marshal(b, m, deterministic)
}
func (m *RspRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRegisterService.Merge(m, src)
}
func (m *RspRegisterService) XXX_Size() int {
	return xxx_messageInfo_RspRegisterService.Size(m)
}
func (m *RspRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_RspRegisterService proto.InternalMessageInfo

func (m *RspRegisterService) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

func (m *RspRegisterService) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ReqUnRegisterService struct {
	AddrHandle           uint64   `protobuf:"varint,1,opt,name=AddrHandle,proto3" json:"AddrHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnRegisterService) Reset()         { *m = ReqUnRegisterService{} }
func (m *ReqUnRegisterService) String() string { return proto.CompactTextString(m) }
func (*ReqUnRegisterService) ProtoMessage()    {}
func (*ReqUnRegisterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{5}
}

func (m *ReqUnRegisterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnRegisterService.Unmarshal(m, b)
}
func (m *ReqUnRegisterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnRegisterService.Marshal(b, m, deterministic)
}
func (m *ReqUnRegisterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnRegisterService.Merge(m, src)
}
func (m *ReqUnRegisterService) XXX_Size() int {
	return xxx_messageInfo_ReqUnRegisterService.Size(m)
}
func (m *ReqUnRegisterService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnRegisterService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnRegisterService proto.InternalMessageInfo

func (m *ReqUnRegisterService) GetAddrHandle() uint64 {
	if m != nil {
		return m.AddrHandle
	}
	return 0
}

//通知服务上下线相关
type NotifyServiceOnline struct {
	ServerAddr           string       `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`
	ServiceInfo          *ServiceInfo `protobuf:"bytes,2,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	IsOnline             bool         `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceOnline) Reset()         { *m = NotifyServiceOnline{} }
func (m *NotifyServiceOnline) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceOnline) ProtoMessage()    {}
func (*NotifyServiceOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{6}
}

func (m *NotifyServiceOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceOnline.Unmarshal(m, b)
}
func (m *NotifyServiceOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceOnline.Marshal(b, m, deterministic)
}
func (m *NotifyServiceOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceOnline.Merge(m, src)
}
func (m *NotifyServiceOnline) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceOnline.Size(m)
}
func (m *NotifyServiceOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceOnline.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceOnline proto.InternalMessageInfo

func (m *NotifyServiceOnline) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *NotifyServiceOnline) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *NotifyServiceOnline) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

//跨进程服务消息通知
type NotifyServiceMessage struct {
	SrcService           *ServiceInfo `protobuf:"bytes,1,opt,name=src_service,json=srcService,proto3" json:"src_service,omitempty"`
	DstHandle            uint64       `protobuf:"varint,2,opt,name=dst_handle,json=dstHandle,proto3" json:"dst_handle,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceMessage) Reset()         { *m = NotifyServiceMessage{} }
func (m *NotifyServiceMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceMessage) ProtoMessage()    {}
func (*NotifyServiceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{7}
}

func (m *NotifyServiceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceMessage.Unmarshal(m, b)
}
func (m *NotifyServiceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceMessage.Marshal(b, m, deterministic)
}
func (m *NotifyServiceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceMessage.Merge(m, src)
}
func (m *NotifyServiceMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceMessage.Size(m)
}
func (m *NotifyServiceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceMessage proto.InternalMessageInfo

func (m *NotifyServiceMessage) GetSrcService() *ServiceInfo {
	if m != nil {
		return m.SrcService
	}
	return nil
}

func (m *NotifyServiceMessage) GetDstHandle() uint64 {
	if m != nil {
		return m.DstHandle
	}
	return 0
}

func (m *NotifyServiceMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//Agent服务与NameServer心跳
type NotifyNameServerHeartBeat struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerHeartBeat) Reset()         { *m = NotifyNameServerHeartBeat{} }
func (m *NotifyNameServerHeartBeat) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerHeartBeat) ProtoMessage()    {}
func (*NotifyNameServerHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{8}
}

func (m *NotifyNameServerHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Unmarshal(m, b)
}
func (m *NotifyNameServerHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerHeartBeat.Merge(m, src)
}
func (m *NotifyNameServerHeartBeat) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerHeartBeat.Size(m)
}
func (m *NotifyNameServerHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerHeartBeat proto.InternalMessageInfo

func (m *NotifyNameServerHeartBeat) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

//通过NameServer同步Service属性变更
type NotifyNameServerSyncAttr struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerSyncAttr) Reset()         { *m = NotifyNameServerSyncAttr{} }
func (m *NotifyNameServerSyncAttr) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerSyncAttr) ProtoMessage()    {}
func (*NotifyNameServerSyncAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{9}
}

func (m *NotifyNameServerSyncAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Unmarshal(m, b)
}
func (m *NotifyNameServerSyncAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerSyncAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerSyncAttr.Merge(m, src)
}
func (m *NotifyNameServerSyncAttr) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerSyncAttr.Size(m)
}
func (m *NotifyNameServerSyncAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerSyncAttr.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerSyncAttr proto.InternalMessageInfo

func (m *NotifyNameServerSyncAttr) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

func (m *NotifyNameServerSyncAttr) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//NameServer同步Agent Service属性变更
type NotifyServiceSyncAttr struct {
	ServiceInfo          *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceSyncAttr) Reset()         { *m = NotifyServiceSyncAttr{} }
func (m *NotifyServiceSyncAttr) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceSyncAttr) ProtoMessage()    {}
func (*NotifyServiceSyncAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{10}
}

func (m *NotifyServiceSyncAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceSyncAttr.Unmarshal(m, b)
}
func (m *NotifyServiceSyncAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceSyncAttr.Marshal(b, m, deterministic)
}
func (m *NotifyServiceSyncAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceSyncAttr.Merge(m, src)
}
func (m *NotifyServiceSyncAttr) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceSyncAttr.Size(m)
}
func (m *NotifyServiceSyncAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceSyncAttr.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceSyncAttr proto.InternalMessageInfo

func (m *NotifyServiceSyncAttr) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *NotifyServiceSyncAttr) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//通知NameServer竞选leader
type NotifyNameServerElection struct {
	SrcHandle            uint64   `protobuf:"varint,1,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	Event                int32    `protobuf:"varint,2,opt,name=Event,proto3" json:"Event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyNameServerElection) Reset()         { *m = NotifyNameServerElection{} }
func (m *NotifyNameServerElection) String() string { return proto.CompactTextString(m) }
func (*NotifyNameServerElection) ProtoMessage()    {}
func (*NotifyNameServerElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{11}
}

func (m *NotifyNameServerElection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyNameServerElection.Unmarshal(m, b)
}
func (m *NotifyNameServerElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyNameServerElection.Marshal(b, m, deterministic)
}
func (m *NotifyNameServerElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyNameServerElection.Merge(m, src)
}
func (m *NotifyNameServerElection) XXX_Size() int {
	return xxx_messageInfo_NotifyNameServerElection.Size(m)
}
func (m *NotifyNameServerElection) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyNameServerElection.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyNameServerElection proto.InternalMessageInfo

func (m *NotifyNameServerElection) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

func (m *NotifyNameServerElection) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

//NameServer通知Service选举结果
type NotifyServiceElectionResult struct {
	Candidate            *ServiceInfo `protobuf:"bytes,1,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
	Event                int32        `protobuf:"varint,2,opt,name=Event,proto3" json:"Event,omitempty"`
	Result               int32        `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotifyServiceElectionResult) Reset()         { *m = NotifyServiceElectionResult{} }
func (m *NotifyServiceElectionResult) String() string { return proto.CompactTextString(m) }
func (*NotifyServiceElectionResult) ProtoMessage()    {}
func (*NotifyServiceElectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{12}
}

func (m *NotifyServiceElectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyServiceElectionResult.Unmarshal(m, b)
}
func (m *NotifyServiceElectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyServiceElectionResult.Marshal(b, m, deterministic)
}
func (m *NotifyServiceElectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyServiceElectionResult.Merge(m, src)
}
func (m *NotifyServiceElectionResult) XXX_Size() int {
	return xxx_messageInfo_NotifyServiceElectionResult.Size(m)
}
func (m *NotifyServiceElectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyServiceElectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyServiceElectionResult proto.InternalMessageInfo

func (m *NotifyServiceElectionResult) GetCandidate() *ServiceInfo {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *NotifyServiceElectionResult) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

func (m *NotifyServiceElectionResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//Agent服务间Ping包
type ReqServicePing struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	DstHandle            uint64   `protobuf:"varint,2,opt,name=DstHandle,proto3" json:"DstHandle,omitempty"`
	SrcServerAddr        string   `protobuf:"bytes,3,opt,name=SrcServerAddr,proto3" json:"SrcServerAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqServicePing) Reset()         { *m = ReqServicePing{} }
func (m *ReqServicePing) String() string { return proto.CompactTextString(m) }
func (*ReqServicePing) ProtoMessage()    {}
func (*ReqServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{13}
}

func (m *ReqServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqServicePing.Unmarshal(m, b)
}
func (m *ReqServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqServicePing.Marshal(b, m, deterministic)
}
func (m *ReqServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqServicePing.Merge(m, src)
}
func (m *ReqServicePing) XXX_Size() int {
	return xxx_messageInfo_ReqServicePing.Size(m)
}
func (m *ReqServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_ReqServicePing proto.InternalMessageInfo

func (m *ReqServicePing) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ReqServicePing) GetDstHandle() uint64 {
	if m != nil {
		return m.DstHandle
	}
	return 0
}

func (m *ReqServicePing) GetSrcServerAddr() string {
	if m != nil {
		return m.SrcServerAddr
	}
	return ""
}

type RspServicePing struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	SrcHandle            uint64   `protobuf:"varint,2,opt,name=SrcHandle,proto3" json:"SrcHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspServicePing) Reset()         { *m = RspServicePing{} }
func (m *RspServicePing) String() string { return proto.CompactTextString(m) }
func (*RspServicePing) ProtoMessage()    {}
func (*RspServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{14}
}

func (m *RspServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspServicePing.Unmarshal(m, b)
}
func (m *RspServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspServicePing.Marshal(b, m, deterministic)
}
func (m *RspServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspServicePing.Merge(m, src)
}
func (m *RspServicePing) XXX_Size() int {
	return xxx_messageInfo_RspServicePing.Size(m)
}
func (m *RspServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_RspServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_RspServicePing proto.InternalMessageInfo

func (m *RspServicePing) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RspServicePing) GetSrcHandle() uint64 {
	if m != nil {
		return m.SrcHandle
	}
	return 0
}

type SSMsg struct {
	Cmd SSCmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=smproto.SSCmd" json:"cmd,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*SSMsg_RegisterAppReq
	//	*SSMsg_RegisterAppRsp
	//	*SSMsg_RegisterServiceReq
	//	*SSMsg_RegisterServiceRsp
	//	*SSMsg_NotifyServiceOnline
	//	*SSMsg_UnregisterServiceReq
	//	*SSMsg_NotifyNameserverHb
	//	*SSMsg_NotifyNameserverAttr
	//	*SSMsg_NotifyServiceAttr
	//	*SSMsg_NotifyNameserverElection
	//	*SSMsg_NotifyServiceElectionResult
	//	*SSMsg_NotifyServiceMessage
	//	*SSMsg_ServicePingReq
	//	*SSMsg_ServicePingRsp
	Msg                  isSSMsg_Msg `protobuf_oneof:"Msg"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SSMsg) Reset()         { *m = SSMsg{} }
func (m *SSMsg) String() string { return proto.CompactTextString(m) }
func (*SSMsg) ProtoMessage()    {}
func (*SSMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a3ff22a5566682, []int{15}
}

func (m *SSMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSMsg.Unmarshal(m, b)
}
func (m *SSMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSMsg.Marshal(b, m, deterministic)
}
func (m *SSMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSMsg.Merge(m, src)
}
func (m *SSMsg) XXX_Size() int {
	return xxx_messageInfo_SSMsg.Size(m)
}
func (m *SSMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SSMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SSMsg proto.InternalMessageInfo

func (m *SSMsg) GetCmd() SSCmd {
	if m != nil {
		return m.Cmd
	}
	return SSCmd_INVALID_CMD
}

type isSSMsg_Msg interface {
	isSSMsg_Msg()
}

type SSMsg_RegisterAppReq struct {
	RegisterAppReq *ReqRegisterApp `protobuf:"bytes,100,opt,name=register_app_req,json=registerAppReq,proto3,oneof"`
}

type SSMsg_RegisterAppRsp struct {
	RegisterAppRsp *RspRegisterApp `protobuf:"bytes,101,opt,name=register_app_rsp,json=registerAppRsp,proto3,oneof"`
}

type SSMsg_RegisterServiceReq struct {
	RegisterServiceReq *ReqRegisterService `protobuf:"bytes,102,opt,name=register_service_req,json=registerServiceReq,proto3,oneof"`
}

type SSMsg_RegisterServiceRsp struct {
	RegisterServiceRsp *RspRegisterService `protobuf:"bytes,103,opt,name=register_service_rsp,json=registerServiceRsp,proto3,oneof"`
}

type SSMsg_NotifyServiceOnline struct {
	NotifyServiceOnline *NotifyServiceOnline `protobuf:"bytes,104,opt,name=notify_service_online,json=notifyServiceOnline,proto3,oneof"`
}

type SSMsg_UnregisterServiceReq struct {
	UnregisterServiceReq *ReqUnRegisterService `protobuf:"bytes,105,opt,name=unregister_service_req,json=unregisterServiceReq,proto3,oneof"`
}

type SSMsg_NotifyNameserverHb struct {
	NotifyNameserverHb *NotifyNameServerHeartBeat `protobuf:"bytes,106,opt,name=notify_nameserver_hb,json=notifyNameserverHb,proto3,oneof"`
}

type SSMsg_NotifyNameserverAttr struct {
	NotifyNameserverAttr *NotifyNameServerSyncAttr `protobuf:"bytes,107,opt,name=notify_nameserver_attr,json=notifyNameserverAttr,proto3,oneof"`
}

type SSMsg_NotifyServiceAttr struct {
	NotifyServiceAttr *NotifyServiceSyncAttr `protobuf:"bytes,108,opt,name=notify_service_attr,json=notifyServiceAttr,proto3,oneof"`
}

type SSMsg_NotifyNameserverElection struct {
	NotifyNameserverElection *NotifyNameServerElection `protobuf:"bytes,109,opt,name=notify_nameserver_election,json=notifyNameserverElection,proto3,oneof"`
}

type SSMsg_NotifyServiceElectionResult struct {
	NotifyServiceElectionResult *NotifyServiceElectionResult `protobuf:"bytes,110,opt,name=notify_service_election_result,json=notifyServiceElectionResult,proto3,oneof"`
}

type SSMsg_NotifyServiceMessage struct {
	NotifyServiceMessage *NotifyServiceMessage `protobuf:"bytes,200,opt,name=notify_service_message,json=notifyServiceMessage,proto3,oneof"`
}

type SSMsg_ServicePingReq struct {
	ServicePingReq *ReqServicePing `protobuf:"bytes,201,opt,name=service_ping_req,json=servicePingReq,proto3,oneof"`
}

type SSMsg_ServicePingRsp struct {
	ServicePingRsp *RspServicePing `protobuf:"bytes,202,opt,name=service_ping_rsp,json=servicePingRsp,proto3,oneof"`
}

func (*SSMsg_RegisterAppReq) isSSMsg_Msg() {}

func (*SSMsg_RegisterAppRsp) isSSMsg_Msg() {}

func (*SSMsg_RegisterServiceReq) isSSMsg_Msg() {}

func (*SSMsg_RegisterServiceRsp) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceOnline) isSSMsg_Msg() {}

func (*SSMsg_UnregisterServiceReq) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverHb) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverAttr) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceAttr) isSSMsg_Msg() {}

func (*SSMsg_NotifyNameserverElection) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceElectionResult) isSSMsg_Msg() {}

func (*SSMsg_NotifyServiceMessage) isSSMsg_Msg() {}

func (*SSMsg_ServicePingReq) isSSMsg_Msg() {}

func (*SSMsg_ServicePingRsp) isSSMsg_Msg() {}

func (m *SSMsg) GetMsg() isSSMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SSMsg) GetRegisterAppReq() *ReqRegisterApp {
	if x, ok := m.GetMsg().(*SSMsg_RegisterAppReq); ok {
		return x.RegisterAppReq
	}
	return nil
}

func (m *SSMsg) GetRegisterAppRsp() *RspRegisterApp {
	if x, ok := m.GetMsg().(*SSMsg_RegisterAppRsp); ok {
		return x.RegisterAppRsp
	}
	return nil
}

func (m *SSMsg) GetRegisterServiceReq() *ReqRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_RegisterServiceReq); ok {
		return x.RegisterServiceReq
	}
	return nil
}

func (m *SSMsg) GetRegisterServiceRsp() *RspRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_RegisterServiceRsp); ok {
		return x.RegisterServiceRsp
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceOnline() *NotifyServiceOnline {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceOnline); ok {
		return x.NotifyServiceOnline
	}
	return nil
}

func (m *SSMsg) GetUnregisterServiceReq() *ReqUnRegisterService {
	if x, ok := m.GetMsg().(*SSMsg_UnregisterServiceReq); ok {
		return x.UnregisterServiceReq
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverHb() *NotifyNameServerHeartBeat {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverHb); ok {
		return x.NotifyNameserverHb
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverAttr() *NotifyNameServerSyncAttr {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverAttr); ok {
		return x.NotifyNameserverAttr
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceAttr() *NotifyServiceSyncAttr {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceAttr); ok {
		return x.NotifyServiceAttr
	}
	return nil
}

func (m *SSMsg) GetNotifyNameserverElection() *NotifyNameServerElection {
	if x, ok := m.GetMsg().(*SSMsg_NotifyNameserverElection); ok {
		return x.NotifyNameserverElection
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceElectionResult() *NotifyServiceElectionResult {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceElectionResult); ok {
		return x.NotifyServiceElectionResult
	}
	return nil
}

func (m *SSMsg) GetNotifyServiceMessage() *NotifyServiceMessage {
	if x, ok := m.GetMsg().(*SSMsg_NotifyServiceMessage); ok {
		return x.NotifyServiceMessage
	}
	return nil
}

func (m *SSMsg) GetServicePingReq() *ReqServicePing {
	if x, ok := m.GetMsg().(*SSMsg_ServicePingReq); ok {
		return x.ServicePingReq
	}
	return nil
}

func (m *SSMsg) GetServicePingRsp() *RspServicePing {
	if x, ok := m.GetMsg().(*SSMsg_ServicePingRsp); ok {
		return x.ServicePingRsp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SSMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SSMsg_RegisterAppReq)(nil),
		(*SSMsg_RegisterAppRsp)(nil),
		(*SSMsg_RegisterServiceReq)(nil),
		(*SSMsg_RegisterServiceRsp)(nil),
		(*SSMsg_NotifyServiceOnline)(nil),
		(*SSMsg_UnregisterServiceReq)(nil),
		(*SSMsg_NotifyNameserverHb)(nil),
		(*SSMsg_NotifyNameserverAttr)(nil),
		(*SSMsg_NotifyServiceAttr)(nil),
		(*SSMsg_NotifyNameserverElection)(nil),
		(*SSMsg_NotifyServiceElectionResult)(nil),
		(*SSMsg_NotifyServiceMessage)(nil),
		(*SSMsg_ServicePingReq)(nil),
		(*SSMsg_ServicePingRsp)(nil),
	}
}

func init() {
	proto.RegisterEnum("smproto.SSCmd", SSCmd_name, SSCmd_value)
	proto.RegisterEnum("smproto.SSError", SSError_name, SSError_value)
	proto.RegisterType((*ReqRegisterApp)(nil), "smproto.ReqRegisterApp")
	proto.RegisterType((*RspRegisterApp)(nil), "smproto.RspRegisterApp")
	proto.RegisterType((*ServiceInfo)(nil), "smproto.ServiceInfo")
	proto.RegisterType((*ReqRegisterService)(nil), "smproto.ReqRegisterService")
	proto.RegisterType((*RspRegisterService)(nil), "smproto.RspRegisterService")
	proto.RegisterType((*ReqUnRegisterService)(nil), "smproto.ReqUnRegisterService")
	proto.RegisterType((*NotifyServiceOnline)(nil), "smproto.NotifyServiceOnline")
	proto.RegisterType((*NotifyServiceMessage)(nil), "smproto.NotifyServiceMessage")
	proto.RegisterType((*NotifyNameServerHeartBeat)(nil), "smproto.NotifyNameServerHeartBeat")
	proto.RegisterType((*NotifyNameServerSyncAttr)(nil), "smproto.NotifyNameServerSyncAttr")
	proto.RegisterType((*NotifyServiceSyncAttr)(nil), "smproto.NotifyServiceSyncAttr")
	proto.RegisterType((*NotifyNameServerElection)(nil), "smproto.NotifyNameServerElection")
	proto.RegisterType((*NotifyServiceElectionResult)(nil), "smproto.NotifyServiceElectionResult")
	proto.RegisterType((*ReqServicePing)(nil), "smproto.ReqServicePing")
	proto.RegisterType((*RspServicePing)(nil), "smproto.RspServicePing")
	proto.RegisterType((*SSMsg)(nil), "smproto.SSMsg")
}

func init() { proto.RegisterFile("ssproto.proto", fileDescriptor_38a3ff22a5566682) }

var fileDescriptor_38a3ff22a5566682 = []byte{
	// 1128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4b, 0x73, 0xe3, 0x44,
	0x17, 0xb5, 0xe3, 0x49, 0x3c, 0xb9, 0x99, 0x49, 0xf4, 0x75, 0x9c, 0x8c, 0x26, 0xce, 0xe4, 0xcb,
	0x88, 0xa9, 0x62, 0x6a, 0x16, 0x59, 0x84, 0x02, 0x8a, 0x1d, 0x8a, 0xd3, 0x13, 0xab, 0xb0, 0x65,
	0xd3, 0xed, 0xa4, 0x2a, 0x2b, 0x95, 0x62, 0x75, 0x1c, 0x31, 0xb1, 0xac, 0xa8, 0x35, 0x53, 0x35,
	0x2b, 0x66, 0xcf, 0x1e, 0xf8, 0x07, 0xfc, 0x0d, 0x96, 0xc0, 0x0a, 0xf8, 0x15, 0xbc, 0x5f, 0x2b,
	0x76, 0x50, 0x6a, 0xbd, 0x1f, 0x71, 0x00, 0x2f, 0x5c, 0xea, 0xdb, 0x7d, 0xcf, 0x3d, 0xf7, 0xf4,
	0xd5, 0x11, 0xdc, 0xe5, 0xdc, 0xf5, 0x66, 0xfe, 0x6c, 0x4f, 0xfc, 0xa3, 0x26, 0x9f, 0x8a, 0x07,
	0xe5, 0x29, 0xac, 0x12, 0x76, 0x45, 0xd8, 0xc4, 0xe6, 0x3e, 0xf3, 0x54, 0xd7, 0x45, 0x3b, 0x00,
	0x94, 0x79, 0x2f, 0x98, 0xa7, 0x5a, 0x96, 0x27, 0xd7, 0x77, 0xeb, 0x8f, 0x97, 0x49, 0x26, 0x82,
	0x5a, 0xb0, 0xa8, 0xba, 0xae, 0x76, 0x28, 0x2f, 0x88, 0xad, 0x70, 0xa1, 0x3c, 0x86, 0x55, 0xc2,
	0xdd, 0x2c, 0xce, 0x26, 0x2c, 0x11, 0xc6, 0x9f, 0x5f, 0xfa, 0xe2, 0xe0, 0x22, 0x89, 0x56, 0xca,
	0x14, 0x56, 0x02, 0x34, 0x7b, 0xcc, 0x34, 0xe7, 0x7c, 0x86, 0x76, 0x93, 0xa5, 0x6e, 0x4e, 0x59,
	0x54, 0x2f, 0x1b, 0x42, 0xdb, 0xb0, 0x1c, 0x27, 0x58, 0x02, 0xeb, 0x16, 0x49, 0x03, 0x01, 0xdd,
	0x80, 0x56, 0xd7, 0x74, 0xac, 0x4b, 0x26, 0x37, 0xc4, 0x76, 0x26, 0xa2, 0xf4, 0x01, 0x65, 0x1a,
	0x8c, 0xf2, 0xd0, 0xdb, 0x70, 0x87, 0x87, 0x8f, 0x86, 0xed, 0x9c, 0xcf, 0x44, 0xd9, 0x95, 0xfd,
	0xd6, 0x5e, 0x24, 0xcb, 0x5e, 0x86, 0x21, 0x59, 0xe1, 0xe9, 0x42, 0xe9, 0x01, 0xca, 0xf4, 0x19,
	0xc3, 0xe5, 0x49, 0xd4, 0x8b, 0x24, 0xae, 0xd5, 0xe2, 0x2d, 0x68, 0x11, 0x76, 0x75, 0xec, 0xfc,
	0x4b, 0x3c, 0xe5, 0xa3, 0x3a, 0xac, 0xeb, 0x33, 0xdf, 0x3e, 0x7f, 0x19, 0x65, 0x0c, 0x9c, 0x4b,
	0xdb, 0x61, 0x37, 0xde, 0x5d, 0xb1, 0xed, 0x85, 0x7f, 0xd8, 0x36, 0x6a, 0xc3, 0xb2, 0xcd, 0x8d,
	0x99, 0xa8, 0x22, 0x44, 0xbe, 0x4d, 0x6e, 0xdb, 0x3c, 0xac, 0xaa, 0xbc, 0xaa, 0x43, 0x2b, 0xc7,
	0xa6, 0xcf, 0x38, 0x37, 0x27, 0x0c, 0xbd, 0x09, 0x2b, 0xdc, 0x1b, 0x1b, 0x11, 0xd0, 0x5c, 0x91,
	0x81, 0x7b, 0xe3, 0xb8, 0xfb, 0x07, 0x00, 0x16, 0xf7, 0x8d, 0x8b, 0xb0, 0xfb, 0xe8, 0xc6, 0x2d,
	0xee, 0x47, 0x62, 0x22, 0xb8, 0x65, 0x99, 0xbe, 0x29, 0x68, 0xdc, 0x21, 0xe2, 0x59, 0x79, 0x07,
	0xee, 0x87, 0x0c, 0x82, 0x89, 0x09, 0x1b, 0xee, 0x32, 0xd3, 0xf3, 0x0f, 0x98, 0xe9, 0x8b, 0x01,
	0xf2, 0xc6, 0x39, 0x31, 0xd3, 0x80, 0xd2, 0x03, 0xb9, 0x98, 0x4a, 0x5f, 0x3a, 0x63, 0xd5, 0xf7,
	0xbd, 0xf9, 0x99, 0x09, 0x91, 0x85, 0x0c, 0x11, 0x0b, 0x36, 0x72, 0x52, 0x24, 0x50, 0xff, 0x75,
	0xe2, 0x2a, 0xab, 0xe8, 0x65, 0xce, 0xf8, 0x92, 0x8d, 0x7d, 0x7b, 0xe6, 0xdc, 0xc0, 0xb9, 0x05,
	0x8b, 0xf8, 0x05, 0x73, 0xe2, 0x41, 0x0c, 0x17, 0xca, 0x87, 0xd0, 0xce, 0xb1, 0x8e, 0xc1, 0xc2,
	0x31, 0x45, 0xfb, 0xb0, 0xdc, 0x31, 0x1d, 0xcb, 0xb6, 0x4c, 0x7f, 0xfe, 0x2d, 0xa6, 0xc7, 0xaa,
	0x0b, 0x65, 0x5e, 0x84, 0x46, 0xee, 0x45, 0x38, 0x17, 0x36, 0x14, 0x41, 0x0d, 0x6d, 0x67, 0x82,
	0x24, 0x68, 0x50, 0x76, 0x15, 0x35, 0x10, 0x3c, 0x06, 0x8d, 0x1d, 0xc6, 0x43, 0x10, 0x4f, 0x45,
	0x12, 0x40, 0x8f, 0xe0, 0x2e, 0x0d, 0x47, 0x28, 0x9a, 0xfe, 0x86, 0x98, 0xfe, 0x7c, 0x50, 0x79,
	0x57, 0xd8, 0xd4, 0x8d, 0x75, 0x52, 0x01, 0x17, 0x8a, 0xe3, 0xf2, 0xf9, 0x32, 0x2c, 0x52, 0xda,
	0xe7, 0x13, 0xb4, 0x0b, 0x8d, 0xf1, 0xd4, 0x12, 0x99, 0xab, 0xfb, 0xab, 0xa9, 0x1e, 0xb4, 0x33,
	0xb5, 0x48, 0xb0, 0x85, 0x3a, 0x20, 0x79, 0xd1, 0x9b, 0x6d, 0x98, 0xae, 0x6b, 0x78, 0xec, 0x4a,
	0xb6, 0x84, 0x7c, 0xf7, 0x92, 0xe3, 0x79, 0xf7, 0xed, 0xd6, 0xc8, 0xaa, 0x97, 0x2e, 0x09, 0xbb,
	0x2a, 0x83, 0x70, 0x57, 0x66, 0x45, 0x90, 0x9c, 0xf5, 0x16, 0x41, 0xb8, 0x8b, 0x06, 0xd0, 0x4a,
	0x40, 0xe2, 0x31, 0x0c, 0xd8, 0x9c, 0x0b, 0xa0, 0x76, 0x15, 0x9b, 0x48, 0xa4, 0x6e, 0x8d, 0x20,
	0x2f, 0x1f, 0x0a, 0x58, 0x55, 0x02, 0x72, 0x57, 0x9e, 0x14, 0x01, 0x4b, 0x66, 0x59, 0x05, 0xc8,
	0x5d, 0x44, 0x60, 0xc3, 0x11, 0x23, 0x98, 0xc0, 0x45, 0x6e, 0x73, 0x21, 0x10, 0xb7, 0x13, 0xc4,
	0x0a, 0xdf, 0xeb, 0xd6, 0xc8, 0xba, 0x53, 0x61, 0x87, 0xc7, 0xb0, 0xf9, 0xdc, 0xa9, 0xec, 0xdb,
	0x16, 0xa0, 0x0f, 0xb2, 0x7d, 0x97, 0x5c, 0xb8, 0x5b, 0x23, 0xad, 0x34, 0x3d, 0xd3, 0xfb, 0x09,
	0xb4, 0x22, 0xaa, 0x8e, 0x39, 0x65, 0x5c, 0x4c, 0x97, 0x71, 0x71, 0x26, 0x7f, 0x20, 0x40, 0x95,
	0x02, 0xd3, 0x0a, 0x47, 0x0a, 0x24, 0x70, 0x92, 0xcd, 0x10, 0xa0, 0x7b, 0x86, 0x4e, 0x61, 0xb3,
	0x8c, 0x6b, 0xfa, 0xbe, 0x27, 0x3f, 0x13, 0xc8, 0x0f, 0xaf, 0x45, 0x8e, 0x5d, 0x26, 0xa0, 0x5c,
	0x04, 0x16, 0xee, 0x33, 0x84, 0xf5, 0x82, 0xba, 0x02, 0xf7, 0x52, 0xe0, 0xee, 0x54, 0x6b, 0x9b,
	0x01, 0xfd, 0x5f, 0x4e, 0x5d, 0x81, 0x68, 0xc2, 0x56, 0x99, 0x2c, 0x8b, 0x7c, 0x43, 0x9e, 0xde,
	0x40, 0x38, 0x36, 0x98, 0x6e, 0x8d, 0xc8, 0x45, 0xc2, 0x89, 0x93, 0x3d, 0x83, 0x9d, 0x02, 0xe9,
	0x18, 0xdf, 0xf0, 0x42, 0x13, 0x71, 0x44, 0x99, 0x47, 0xd5, 0xfc, 0xf3, 0x26, 0xd6, 0xad, 0x91,
	0xb6, 0x33, 0xc7, 0xe3, 0x4e, 0x12, 0xf1, 0xe3, 0x62, 0xd3, 0xf0, 0x2b, 0x26, 0x7f, 0x51, 0x2f,
	0x0c, 0x4b, 0xd5, 0xb7, 0x2e, 0x55, 0xbe, 0xf0, 0x0d, 0x3c, 0x04, 0x29, 0x06, 0x74, 0x6d, 0x67,
	0x22, 0xa6, 0xef, 0xcb, 0x7a, 0xd9, 0x04, 0x32, 0x9e, 0x14, 0xbc, 0xbf, 0x3c, 0x5d, 0x06, 0x23,
	0x57, 0x42, 0xe1, 0xae, 0xfc, 0x55, 0xbd, 0xec, 0x02, 0x73, 0x50, 0xb8, 0x7b, 0xb0, 0x08, 0x8d,
	0x3e, 0x9f, 0x3c, 0xf9, 0xac, 0x11, 0x58, 0x58, 0x67, 0x6a, 0xa1, 0x35, 0x58, 0xd1, 0xf4, 0x13,
	0xb5, 0xa7, 0x1d, 0x1a, 0x9d, 0xfe, 0xa1, 0x54, 0x43, 0x1b, 0x20, 0x11, 0xfc, 0xbe, 0x41, 0xf0,
	0x91, 0x46, 0x47, 0x98, 0x18, 0xea, 0x70, 0x28, 0x7d, 0xd7, 0x14, 0x61, 0x3a, 0xcc, 0x87, 0xbf,
	0x6f, 0xa2, 0xfb, 0xd0, 0xca, 0x9d, 0xa6, 0x98, 0x9c, 0x68, 0x1d, 0x2c, 0xfd, 0x10, 0x6e, 0x65,
	0x33, 0xe2, 0xad, 0x1f, 0x9b, 0x68, 0x0b, 0x36, 0xf4, 0xc1, 0x48, 0x7b, 0x7a, 0x1a, 0x07, 0x8d,
	0x81, 0xde, 0xd3, 0x74, 0x2c, 0xfd, 0xd4, 0x44, 0x6d, 0xd8, 0x0c, 0x10, 0x8f, 0xf5, 0x52, 0xe2,
	0xcf, 0x4d, 0xb4, 0x0b, 0xed, 0x28, 0x51, 0x57, 0xfb, 0x38, 0xd8, 0xc0, 0xc4, 0xe8, 0x62, 0x95,
	0x8c, 0x0e, 0xb0, 0x3a, 0x92, 0x7e, 0x69, 0xa2, 0xff, 0xc3, 0x56, 0xf9, 0x04, 0x3d, 0xd5, 0x3b,
	0xea, 0x68, 0x44, 0xa4, 0x5f, 0x9b, 0x68, 0x1b, 0xee, 0x15, 0x6a, 0x27, 0xbb, 0xbf, 0x5d, 0x93,
	0x8e, 0x7b, 0xb8, 0x33, 0xd2, 0x06, 0xba, 0xf4, 0x7b, 0x13, 0xbd, 0x06, 0x3b, 0x85, 0xf4, 0x78,
	0xd7, 0x20, 0x98, 0x1e, 0xf7, 0x46, 0xd2, 0x1f, 0xa2, 0x87, 0xc2, 0xa1, 0x3e, 0xa6, 0x54, 0x3d,
	0xc2, 0xd2, 0xd7, 0x6b, 0xb1, 0xc0, 0x43, 0x4d, 0x3f, 0x4a, 0x5a, 0xfb, 0x66, 0x2d, 0x16, 0x38,
	0x17, 0xfe, 0x76, 0xed, 0xc9, 0xab, 0x3a, 0x34, 0x29, 0xc5, 0x9e, 0x37, 0xf3, 0xd0, 0x12, 0x2c,
	0x0c, 0xde, 0x93, 0x6a, 0xe8, 0x21, 0xb4, 0x30, 0x11, 0x57, 0x60, 0xe8, 0x83, 0x51, 0xa2, 0xb0,
	0xf4, 0xe9, 0x9f, 0x7f, 0x85, 0xbf, 0x3a, 0x7a, 0x1d, 0xb6, 0x82, 0x23, 0x71, 0xf9, 0xf4, 0xda,
	0x8e, 0x54, 0x4d, 0x97, 0x3e, 0x49, 0x0f, 0x66, 0xb0, 0x28, 0xa6, 0x34, 0xe8, 0xa3, 0x37, 0xa0,
	0x23, 0xe9, 0xe3, 0xe4, 0xc8, 0xd9, 0x92, 0x98, 0xad, 0x37, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x5e, 0xc1, 0x6c, 0x10, 0x41, 0x0c, 0x00, 0x00,
}
